### ISSUE TITLE
Problem using json-schema in Android

### ISSUE THREAD

**Issue by josdejong** [everit-org/json-schema#10]
Thanks for writing this library, it looks neat and easy to use.

I have trouble however using the library on Android. I'm not sure if this is supposed to work at all, but when I add the following dependency to my build.gradle:

```
dependencies {
    // ...
    compile 'org.everit.json:org.everit.json.schema:1.0.1'
}
```

I get the following error when building:

```
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
	at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
	at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
	at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
	at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
	at com.android.dx.command.dexer.Main.processClass(Main.java:704)
	at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
	at com.android.dx.command.dexer.Main.access$300(Main.java:83)
	at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
	at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
	at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
	at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
	at com.android.dx.command.dexer.Main.processOne(Main.java:632)
	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
...while parsing org/everit/json/schema/ArraySchema$Builder.class
1 error; aborting
Error:Execution failed for task ':preDexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/usr/lib/jvm/jdk1.7.0_79/bin/java'' finished with non-zero exit value 1
```

Any idea on how to solve this?

**Comment by josdejong** [comment]
I think I found the reason: `json-schema` uses Java 8 features, and Java 8 isn't supported on Android. End of story :(.

**Comment by erosb** [comment]
Yes, thats the case, sadly.

**Comment by dinhthaidaica** [comment]
Hi guy, is there any way to add this awesome library by grade for my android project ?

**Comment by erosb** [comment]
Not really. You may be able to make an old version compile on java6.

Since the library widely uses java8 features, making it java6 compliant is not easy. Previously a PR was created which makes version 1.0.1 work on java6: https://github.com/everit-org/json-schema/pull/19

If you feel curious then you can try by compiling this fork: https://github.com/rdruilhe/json-schema
