### ISSUE TITLE
Schema Exception

### ISSUE THREAD

**Issue by dbeja** [everit-org/json-schema#109]
Hi,

I'm trying using this schema validation file: https://realtime-listings.webservices.zpg.co.uk/docs/latest/schemas/listing/update.json

But when I use your lib I get this exception:

```
org.everit.json.schema.SchemaException: #/constraints/residential: expected at most 1 of 'allOf', 'anyOf', 'oneOf', 2 found
	at org.everit.json.schema.loader.LoadingState.createSchemaException(LoadingState.java:147) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.CombinedSchemaLoader.load(CombinedSchemaLoader.java:54) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:356) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:44) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:383) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.ReferenceLookup.performQueryEvaluation(ReferenceLookup.java:125) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.ReferenceLookup.lookup(ReferenceLookup.java:135) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.buildSchemaWithoutExplicitType(SchemaLoader.java:321) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.lambda$loadSchemaObject$5(SchemaLoader.java:359) ~[org.everit.json.schema-1.6.0.jar:na]
	at java.util.Optional.orElseGet(Optional.java:267) ~[na:1.8.0_91]
	at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:357) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:44) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:383) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:426) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.CombinedSchemaLoader.lambda$load$0(CombinedSchemaLoader.java:60) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.JsonArray.forEach(JsonArray.java:24) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.CombinedSchemaLoader.load(CombinedSchemaLoader.java:59) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:356) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:44) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:383) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:426) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.CombinedSchemaLoader.lambda$load$0(CombinedSchemaLoader.java:60) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.JsonArray.forEach(JsonArray.java:24) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.CombinedSchemaLoader.load(CombinedSchemaLoader.java:59) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:356) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:44) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:383) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:219) ~[org.everit.json.schema-1.6.0.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:202) ~[org.everit.json.schema-1.6.0.jar:na]

```

I'm not understanding what's wrong on this schema file.

Thanks!

**Comment by erosb** [comment]
Hello,

you use both `"anyOf"` and `"allOf"` in the `#/constraints/residential` subschema. The library doesn't recognize this combination of keywords.

This schema looks a bit odd for me, but if you are sure you want to use `"properties"` and `"anyOf"` and `"oneOf"` at the same level, then I recommend creating an umbrella `"allOf"` wrapping them, like 

```
"constraints" : {
  "residential": {
    "allOf": [
      {
        "properties": ...
      },
      {
        "anyOf": ...
      },
      {
        "oneOf": ...
      }
    ]
  }
}
```
