### ISSUE TITLE
ObjectSchema.getAdditionalPropeties throws NPE on empty object

### ISSUE THREAD

**Issue by andrejserafim** [everit-org/json-schema#12]
For example
```java
  @Test
  public void validateMetaSchema() {

    JSONObject jsonSchema = new JSONObject(new JSONTokener(
        MetaSchemaTest.class
            .getResourceAsStream("/org/everit/json/schema/json-schema-draft-04.json")));

    JSONObject jsonSubject = new JSONObject("{\n" +
            "  \"type\": \"object\",\n" +
            "  \"properties\": {}\n" +
            "}");

    Schema schema = SchemaLoader.load(jsonSchema);
    schema.validate(jsonSubject);
  }
```

throws 

```
java.lang.NullPointerException
	at java.util.Arrays.stream(Arrays.java:5004)
	at org.everit.json.schema.ObjectSchema.getAdditionalProperties(ObjectSchema.java:259)
	at org.everit.json.schema.ObjectSchema.testAdditionalProperties(ObjectSchema.java:251)
	at org.everit.json.schema.ObjectSchema.validate(ObjectSchema.java:320)
	at org.everit.json.schema.ObjectSchema.testProperties(ObjectSchema.java:269)
	at org.everit.json.schema.ObjectSchema.validate(ObjectSchema.java:318)
...
```

This is because JSONObject.getNames(subject) can return null. Do you mind if I raise a PR to fix?

**Comment by erosb** [comment]
@andrejserafim @wizmerhill the fix has been released with 1.0.0 (already available on maven central)
