### ISSUE TITLE
org.json.JSONObject toMap() NoSuchMethodError

### ISSUE THREAD

**Issue by mrrllbb** [everit-org/json-schema#130]
I am trying json schema in Java through this package and I follow your guide to start. But I met some stupid Error about org.json.JSONObject. 

I read your load method of the class SchemaLoader, and it has a step containing 'toMap()'. However, when I run my code, I got "java.lang.NoSuchMethodError: org.json.JSONObject.toMap()Ljava/util/Map;" 

Is my json package too old?

Following is my code:

> public boolean isSchema(HashMap<String, Object> schema) throws IOException, JSONException {
 		// TODO Auto-generated method stub
 		JSONObject jsonSchema = new JSONObject(schema);
 		try (InputStream inputStream = this.getClass().getClassLoader().getResourceAsStream("schema")) {
 			  JSONObject rawSchema = new JSONObject(new JSONTokener(new InputStreamReader(inputStream)));
			  Schema validation = SchemaLoader.load(rawSchema);
 			  validation.validate(jsonSchema);
		}catch (ValidationException e) {
 			  System.out.println(e.getMessage());
 			  return false;
 			}
 		return true; 	}

And my Error:

```
 Caused by: java.lang.NoSuchMethodError: org.json.JSONObject.toMap()Ljava/util/Map;
	at org.everit.json.schema.loader.SchemaLoader$SchemaLoaderBuilder.schemaJson(SchemaLoader.java:160)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:216)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:202)
	at com.cn.saic.scm.ai.dataengine.service.SchemaServiceImplement.isSchema(SchemaServiceImplement.java:25)
	at com.cn.saic.scm.ai.dataengine.service.SchemaServiceImplement$$FastClassBySpringCGLIB$$9ba42ca5.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:738)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.aop.aspectj.MethodInvocationProceedingJoinPoint.proceed(MethodInvocationProceedingJoinPoint.java:85)
	at com.cn.saic.scm.ai.dataengine.aop.logging.LoggingAspect.logAround(LoggingAspect.java:85)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethodWithGivenArgs(AbstractAspectJAdvice.java:629)
	at org.springframework.aop.aspectj.AbstractAspectJAdvice.invokeAdviceMethod(AbstractAspectJAdvice.java:618)
	at org.springframework.aop.aspectj.AspectJAroundAdvice.invoke(AspectJAroundAdvice.java:70)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.aspectj.AspectJAfterThrowingAdvice.invoke(AspectJAfterThrowingAdvice.java:62)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:92)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:673)
	at com.cn.saic.scm.ai.dataengine.service.SchemaServiceImplement$$EnhancerBySpringCGLIB$$b9b92c8d.isSchema(<generated>)
	at com.cn.saic.scm.ai.dataengine.resource.JsonSchemaResource.createJsonSchema(JsonSchemaResource.java:93)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:97)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:967)
	... 99 common frames omitted
```

**Comment by mrrllbb** [comment]
Actually my version of json is too old.

**Comment by theabeing** [comment]
> Actually my version of json is too old.

same here. Updating my dependency solved this. thanks for the hint :)
