### ISSUE TITLE
When you defined additionalProperties to false and have an empty object, NPE happens

### ISSUE THREAD

**Issue by wizmerhill** [everit-org/json-schema#15]
In ObjectSchema.getAdditionalProperties if additionalProperties is defined to false we don't test that object is empty. 

Exception in thread "main" java.lang.NullPointerException
	at java.util.Arrays.stream(Arrays.java:5004)
	at org.everit.json.schema.ObjectSchema.getAdditionalProperties(ObjectSchema.java:259)
	at org.everit.json.schema.ObjectSchema.testAdditionalProperties(ObjectSchema.java:247)
	at org.everit.json.schema.ObjectSchema.validate(ObjectSchema.java:320)
	at org.everit.json.schema.ObjectSchema.testProperties(ObjectSchema.java:269)
	at org.everit.json.schema.ObjectSchema.validate(ObjectSchema.java:318)

**Comment by erosb** [comment]
Hello @wizmerhill , could you please post your schema and input document to let me reproduce this issue?

**Comment by erosb** [comment]
nevermind, it is the same bug as the one fixed here: https://github.com/everit-org/json-schema/pull/13
We will release a new version, hopefully this week, it will contain the fix.
