### ISSUE TITLE
Regression with pattern reg-ex

### ISSUE THREAD

**Issue by mountainowl** [everit-org/json-schema#157]
### Issue
Just updated and ran into this issue.
re2j does not support lookahead. 
this was working around version 1.4.1

### Schema
"secret": {
      "type": "string",
      "description": "password",
      "maxLength": 512,
      "pattern": "^(?=.*[\\p{L}\\p{N}\\p{Mn}\\p{Pd}\\p{S}\\p{P}\\d])[\\p{L}\\p{N}\\p{Mn}\\p{Pd}\\p{S}\\p{P}\\d]{8,}"
    },

### Stack trace
```
com.google.re2j.PatternSyntaxException: error parsing regexp: invalid or unsupported Perl syntax: `(?=`
	at com.google.re2j.Parser.parsePerlFlags(Parser.java:1139)
	at com.google.re2j.Parser.parseInternal(Parser.java:825)
	at com.google.re2j.Parser.parse(Parser.java:802)
	at com.google.re2j.RE2.compileImpl(RE2.java:183)
	at com.google.re2j.Pattern.compile(Pattern.java:136)
	at com.google.re2j.Pattern.compile(Pattern.java:96)
	at org.everit.json.schema.StringSchema.<init>(StringSchema.java:103)
	at org.everit.json.schema.StringSchema$Builder.build(StringSchema.java:34)
	at org.everit.json.schema.StringSchema$Builder.build(StringSchema.java:20)
	at org.everit.json.schema.loader.ReferenceLookup.lookup(ReferenceLookup.java:164)
	at org.everit.json.schema.loader.SchemaLoader.buildSchemaWithoutExplicitType(SchemaLoader.java:334)
	at org.everit.json.schema.loader.SchemaLoader.lambda$loadSchemaObject$4(SchemaLoader.java:380)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:378)
	at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:44)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:421)
	at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:464)
	at org.everit.json.schema.loader.ObjectSchemaLoader.addPropertySchemaDefinition(ObjectSchemaLoader.java:68)
	at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$populatePropertySchemas$9(ObjectSchemaLoader.java:62)
	at org.everit.json.schema.loader.JsonObject.iterateOnEntry(JsonObject.java:85)
	at org.everit.json.schema.loader.JsonObject.lambda$forEach$1(JsonObject.java:80)
	at java.util.HashMap$EntrySet.forEach(HashMap.java:1043)
	at org.everit.json.schema.loader.JsonObject.forEach(JsonObject.java:80)
	at org.everit.json.schema.loader.ObjectSchemaLoader.populatePropertySchemas(ObjectSchemaLoader.java:59)
	at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$load$0(ObjectSchemaLoader.java:31)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.everit.json.schema.loader.ObjectSchemaLoader.load(ObjectSchemaLoader.java:31)
	at org.everit.json.schema.loader.SchemaLoader.buildObjectSchema(SchemaLoader.java:446)
	at org.everit.json.schema.loader.SchemaLoader.loadForExplicitType(SchemaLoader.java:439)
	at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:44)
	at org.everit.json.schema.loader.SchemaLoader.loadForType(SchemaLoader.java:456)
	at org.everit.json.schema.loader.SchemaLoader.lambda$loadSchemaObject$4(SchemaLoader.java:382)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:378)
	at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:44)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:421)
	at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:464)
	at org.everit.json.schema.loader.ObjectSchemaLoader.addPropertySchemaDefinition(ObjectSchemaLoader.java:68)
	at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$populatePropertySchemas$9(ObjectSchemaLoader.java:62)
	at org.everit.json.schema.loader.JsonObject.iterateOnEntry(JsonObject.java:85)
	at org.everit.json.schema.loader.JsonObject.lambda$forEach$1(JsonObject.java:80)
	at java.util.HashMap$EntrySet.forEach(HashMap.java:1043)
	at org.everit.json.schema.loader.JsonObject.forEach(JsonObject.java:80)
	at org.everit.json.schema.loader.ObjectSchemaLoader.populatePropertySchemas(ObjectSchemaLoader.java:59)
	at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$load$0(ObjectSchemaLoader.java:31)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.everit.json.schema.loader.ObjectSchemaLoader.load(ObjectSchemaLoader.java:31)
	at org.everit.json.schema.loader.SchemaLoader.buildObjectSchema(SchemaLoader.java:446)
	at org.everit.json.schema.loader.SchemaLoader.loadForExplicitType(SchemaLoader.java:439)
	at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:44)
	at org.everit.json.schema.loader.SchemaLoader.loadForType(SchemaLoader.java:456)
	at org.everit.json.schema.loader.SchemaLoader.lambda$loadSchemaObject$4(SchemaLoader.java:382)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:378)
	at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:44)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:421)
```

**Comment by erosb** [comment]
The fix is available in the latest release: [1.9.0](https://github.com/everit-org/json-schema/releases/tag/1.9.0)
