### ISSUE TITLE
No virtual method toMap()Ljava/util/Map; in class Lorg/json/JSONObject;

### ISSUE THREAD

**Issue by johnygeorge** [everit-org/json-schema#161]
I am getting this exception when I am using this library in Android. I am using the following dependency 

**"com.github.everit-org.json-schema:org.everit.json.schema:1.8.0"**

```
java.lang.NoSuchMethodError: No virtual method toMap()Ljava/util/Map; in class Lorg/json/JSONObject; or its super classes (declaration of 'org.json.JSONObject' appears in /system/framework/core-libart.jar)
at org.everit.json.schema.loader.SchemaLoader$SchemaLoaderBuilder.schemaJson(SchemaLoader.java:175)
at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:250)
at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:236)

```

**Comment by erosb** [comment]
> /system/framework/core-libart.jar

Ok, that rings a bell now. So AFAIR the android devs reimplemented the org.json library and included it in their runtime, but since the the original org.json library changed (including the addition of the `toMap()` method in question), do the two org.json implementations slightly diverged.

So the thing to do is restoring android compatibility. I'm afraid there may also be problems with `$ref` resolutions. The important bit here would be adding a separate integration test suite which runs all integ test in an andoid environment, and that is going to be problematic, because I never worked with android before. Any help is appreciated.

**Comment by zverbatim** [comment]
The same issue was brought here too: https://github.com/everit-org/json-schema/issues/98

This the output for `mvn dependency:tree`
```
[INFO] +- com.github.everit-org.json-schema:org.everit.json.schema:jar:1.8.0:test
[INFO] |  +- org.json:json:jar:20140107:test
[INFO] |  +- com.google.guava:guava:jar:19.0:test
[INFO] |  +- commons-validator:commons-validator:jar:1.6:test
[INFO] |  |  +- commons-beanutils:commons-beanutils:jar:1.9.3:test
[INFO] |  |  +- commons-digester:commons-digester:jar:2.1:test
[INFO] |  |  +- commons-logging:commons-logging:jar:1.2:test
[INFO] |  |  \- commons-collections:commons-collections:jar:3.2.2:test
```

Which is strange since part of the [pom](https://github.com/everit-org/json-schema/blob/b6f9f1eee9e803dfad67cf57e53a501b9a0e9697/core/pom.xml#L136) this is the version used of org.json
```
 <dependency>
            <groupId>org.json</groupId>
            <artifactId>json</artifactId>
            <version>20180130</version>
        </dependency>
```

**Comment by erosb** [comment]
@zverbatim can you please post your complete `pom.xml` ? I still can't reproduce this problem.

**Comment by thijsbaars** [comment]
I'm using `Spring-boot-starter-test` and ran into this issue.
By adding the JSON exclusion, it replaces that implementation with a json module that works.

 ```
<dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-test</artifactId>
            <scope>test</scope>
            <exclusions>
                <exclusion>
                    <groupId>com.vaadin.external.google</groupId>
                    <artifactId>android-json</artifactId>
                </exclusion>
            </exclusions>
        </dependency>
```

**Comment by JoaoGFarias** [comment]
Any update on this?

**Comment by erosb** [comment]
@JoaoGFarias see the solution [above](https://github.com/everit-org/json-schema/issues/161#issuecomment-408059213)

**Comment by joeydh** [comment]
Major problem with this too.

It seems its not possible to get this working for android. Even when the depencies seem correct. When i look at the mvn dependency tree it seems correct. I've the same error even if I just open a new empty android project. 

> +--- com.github.everit-org.json-schema:org.everit.json.schema:1.9.2
> |    +--- org.json:json:20180130
> |    +--- commons-validator:commons-validator:1.6
> |    |    +--- commons-digester:commons-digester:1.8.1
> |    |    +--- commons-logging:commons-logging:1.2
> |    |    \--- commons-collections:commons-collections:3.2.2
> |    +--- commons-beanutils:commons-beanutils:1.9.3
> |    |    +--- commons-logging:commons-logging:1.2
> |    |    \--- commons-collections:commons-collections:3.2.2
> |    +--- com.damnhandy:handy-uri-templates:2.1.6
> |    |    \--- joda-time:joda-time:2.9.4
> |    \--- com.google.re2j:re2j:1.1

Did anyone find a solution for this?

**Comment by erosb** [comment]
Hello, on android the library is reported not to work (don't try to fix it). We will try to do something about it in the next release (hopefully in this year) because it affects several users.

**Comment by joeydh** [comment]
Thanks i've got it working by replacing the toMap and the getNames function
