### ISSUE TITLE
Unable to use "$ref" without "file" protocol

### ISSUE THREAD

**Issue by ankshah** [everit-org/json-schema#222]
I am trying to refer a separate json schema file using `$ref` but getting `Malformed url exception` without adding `file://` before the file name. After adding `file://` , the code expects `BaseJsonSchema.json` in the current directory instead of `data/src/main/resources`

**Schema File: data/src/main/resources/TwitterJsonSchema.json**
```
{
  "description" : "Twitter data",
  "type":"object",
  "allOf":[
     { "$ref":"BaseJsonSchema.json#/definitions/baseData" },
    {
         "properties": {
             "followersCount": {"type":"number" },
          }
     }]
} 
```

**Schema File: data/src/main/resources/BaseJsonSchema.json**
```
{
    "title": "baseData",
   "type":"object",
   "definitions":{
     "baseData": {
          "type": "object",
          "properties": {
                  "sourceUrl": {
                        "type": "string"
                   },
          }
      }
   }
}
```
**Code**:
```
package com.data.commons.validator 

class JsonValidator{

    public static void main(String[] args) {
        validateJsonSchema(args[0], args[1])
    }

    static void validateJsonSchema(String jsonSchemaFile, String json) {
        JSONObject jsonObject = new JSONObject(json)
        Schema schema = SchemaLoader.builder().schemaJson(new JSONObject(new JSONTokener(this.getClass().getResourceAsStream(jsonSchemaFile)))).build().load().build()
        schema.validate(jsonObject)
    }
}
```
**Exception**:
```
Exception in thread "main" java.io.UncheckedIOException: java.net.MalformedURLException: no protocol: BaseJsonSchema.json
	at org.everit.json.schema.loader.internal.DefaultSchemaClient.get(DefaultSchemaClient.java:35)
	at org.everit.json.schema.loader.internal.JSONPointer.executeWith(JSONPointer.java:87)
	at org.everit.json.schema.loader.internal.JSONPointer.lambda$forURL$1(JSONPointer.java:141)
	at org.everit.json.schema.loader.internal.JSONPointer.query(JSONPointer.java:162)
	at org.everit.json.schema.loader.SchemaLoader.lookupReference(SchemaLoader.java:578)
	at org.everit.json.schema.loader.SchemaLoader.buildSchemaWithoutExplicitType(SchemaLoader.java:435)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:517)
	at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:530)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.IntPipeline$4$1.accept(IntPipeline.java:250)
	at java.util.stream.Streams$RangeIntSpliterator.forEachRemaining(Streams.java:110)
	at java.util.Spliterator$OfInt.forEachRemaining(Spliterator.java:693)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
	at org.everit.json.schema.loader.SchemaLoader.tryCombinedSchema(SchemaLoader.java:640)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:514)
	at org.everit.json.schema.loader.SchemaLoader$load$0.call(Unknown Source)
	at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:113)
	at org.codehaus.groovy.runtime.callsite.AbstractCallSite.call(AbstractCallSite.java:117)
	at com.tracxn.data.commons.validator.JsonValidator.validateJsonSchema(JsonValidator.groovy:19)
	at com.tracxn.data.commons.validator.JsonValidator.main(JsonValidator.groovy:11)
Caused by: java.net.MalformedURLException: no protocol: BaseJsonSchema.json
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.everit.json.schema.loader.internal.DefaultSchemaClient.get(DefaultSchemaClient.java:33)
	... 24 more

```

**Comment by erosb** [comment]
Hi! It seems it doesn't work because the library doesn't know where the `TwitterJsonSchema.json` is loaded from. You need to explicitly set a [resolution scope](https://github.com/everit-org/json-schema#resolution-scopes) (eg. `.resolutionScope("file://.../TwitterJsonSchema.json")`)

**Comment by ankshah** [comment]
Hi @erosb , since the json schema files are in the resource folder (bundled in the jar), how do I set the resolutionScope as the jar file? I tried setting resolutionScope to `data/target/data-1.0.0.jar`, but it returns the `java.net.MalformedURLException: no protocol: BaseJsonSchema.json` exceptioned mentioned above. Any pointers please?

**Comment by erosb** [comment]
I'm not sure what version of json schema are you trying to use, but `"id"` works only for draft-4 schemas (which is an old version), and the keyword changed to `"$id"` in draft-6.

Also, the value you set `"jar:file:data/target/data-1.0.0.jar!/TwitterJsonSchema.json"` is not a valid URL so it definitely won't work.

There are multiple ways to make progress on it:
 * the library just uses the URL class of the JDK so the library supports whatever protocol supported by the URL class. If necessary, you can [define your own protocol handler](https://stackoverflow.com/questions/26363573/registering-and-using-a-custom-java-net-url-protocol).
 * alternatively you can use a custom `SchemaClient` interface and wire it into the `SchemaLoader`. This part will look something like this:
```
SchemaLoader loader = SchemaLoader.builder().schemaJson(yourSchemaJson).schemaClient(new YourSchemaClient()).build();
Schema schema = loader.load().build();
```
Then in the `YourSchemaClient` you load the schema from whatever source you would like to. You will be given a String as parameter and should return the InputStream of the found json content.

**Comment by ankshah** [comment]
> I'm not sure what version of json schema are you trying to use, but "id" works only for draft-4 schemas (which is an old version), and the keyword changed to "$id" in draft-6.  

I updated the schema version to  draft-7 and replaced the keyword `id` with `$id`.

> Also, the value you set "jar:file:data/target/data-1.0.0.jar!/TwitterJsonSchema.json" is not a valid URL so it definitely won't work.  

`jar:file:data/target/data-1.0.0.jar!/TwitterJsonSchema.json` is a [JarURL]("jar:file:data/target/data-1.0.0.jar!/TwitterJsonSchema.json") [supported](https://docs.oracle.com/javase/7/docs/api/java/net/URL.html) by java URL class. I verified this by using jar URL `jar:file:data/target/data-1.0.0.jar!/BaseJsonSchema.json` directly in `$ref` variable (without `$id`) - which works. I verified `$id` behaviour using `file:` protocol instead of `jar:file` and placing the json schema files accordingly in the file system. The problem occurs while using jar URL with `$id`

**Comment by erosb** [comment]
> is a JarURL supported by java URL class

Good to know, thanks.

I tested it a bit locally and probably you hit some oddity in the URI class (used by `org.everit.json.schema.loader.internal.ReferenceResolver`). It doesn't seem to properly resolve relative URIs when the scheme contains a colon. So eg. if the relative URI is `BaseSchemaJson.json` and 
 * the base is `jar:file//data/target/data-1.0.0.jar!/TwitterJsonSchema.json` , then URI.resolve() returns `BaseJsonSchema.json`
 * the base is `jar://data/target/data-1.0.0.jar!/TwitterJsonSchema.json` , then `URI.resolve()` returns `jar://data/target/data-1.0.0.jar!/BaseJsonSchema.json` , which is correct, but you get a `MalformedURLException` one step later when you try to open the connection.

It seems you are stuck this way. Probably your best option for now is to use a custom `SchemaClient`.

**Comment by erosb** [comment]
PS. just in case you use spring, then the `classpath://` protocol will work and do exactly what you want to achieve.

**Comment by ankshah** [comment]
> the base is jar://data/target/data-1.0.0.jar!/TwitterJsonSchema.json , then URI.resolve() returns jar://data/target/data-1.0.0.jar!/BaseJsonSchema.json , which is correct, but you get a MalformedURLException one step later when you try to open the connection.    

Okay. Will try to debug this oddity later. Thanks for the pointer. 

I am not using spring. I have worked the issue out by modifying the json schema file at runtime. My base $refs are limited to one or two files, I read the definitions from these files and inject in other schemas at runtime - a bit hackish, but works for my use case. 

Thanks for your time and support @erosb  :+1:
