### ISSUE TITLE
Json Pointers to something identified by $id does not seem to work

### ISSUE THREAD

**Issue by pieterbos** [everit-org/json-schema#244]
according to https://json-schema.org/latest/json-schema-core.html#idExamples , references to a schema such as #foo should return the element with the $id field set to foo. However, this does not seem to work with this json-schema library. Instead it just returns the entire schema. In this case, this schema has no properties - only definitions - and validation succeeds silently, when it should actually fail.
When changed to the #/definitions/... form, this works correctly.

**Comment by erosb** [comment]
Hello, can you please submit a failing test as explained in the  [contribution guideline](https://github.com/everit-org/json-schema/blob/master/CONTRIBUTING.md) ? 

By the way I think if the `"$ref"` is `"#foo"` then the referred `"$id"` must also be `"#foo"` (with the hashmark).

**Comment by pieterbos** [comment]
You're absolutely right, should be #foo, and it was and still did not work :). If I have some spare time I'll try to write a test.

**Comment by erosb** [comment]
Can you please double-check if you use the latest version of the library? (1.9.2)

**Comment by pieterbos** [comment]
I do use the latest version, 1.9.2. 
The problem is a remote pointer, to ```https://www.openEHR.org/releases/ITS-JSON/Release-1.0.0/BASE/latest/Base_types/all.json#OBJECT_REF```. 
Started a debugger. This is the stacktrace where I end up:

```
at org.everit.json.schema.loader.JsonPointerEvaluator.query(JsonPointerEvaluator.java:161)
	at org.everit.json.schema.loader.ReferenceLookup.lookup(ReferenceLookup.java:159)
	at org.everit.json.schema.loader.ReferenceSchemaExtractor.extract(SchemaExtractor.java:163)
	at org.everit.json.schema.loader.AbstractSchemaExtractor.extract(SchemaExtractor.java:80)
	at org.everit.json.schema.loader.SchemaLoader.runSchemaExtractors(SchemaLoader.java:359)
	at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:340)
	at org.everit.json.schema.loader.SchemaLoader$$Lambda$136/2012654961.apply(Unknown Source)
	at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:44)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:410)
	at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:414)
	at org.everit.json.schema.loader.ObjectSchemaLoader.addPropertySchemaDefinition(ObjectSchemaLoader.java:70)
	at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$populatePropertySchemas$9(ObjectSchemaLoader.java:64)
	at org.everit.json.schema.loader.ObjectSchemaLoader$$Lambda$160/1322834162.apply(Unknown Source)
	at org.everit.json.schema.loader.JsonObject.iterateOnEntry(JsonObject.java:84)
	at org.everit.json.schema.loader.JsonObject.lambda$forEach$1(JsonObject.java:79)
	at org.everit.json.schema.loader.JsonObject$$Lambda$161/100312675.accept(Unknown Source)
	at java.util.HashMap$EntrySet.forEach(HashMap.java:1035)
	at org.everit.json.schema.loader.JsonObject.forEach(JsonObject.java:79)
	at org.everit.json.schema.loader.ObjectSchemaLoader.populatePropertySchemas(ObjectSchemaLoader.java:61)
	at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$load$0(ObjectSchemaLoader.java:32)
	at org.everit.json.schema.loader.ObjectSchemaLoader$$Lambda$159/1185581152.accept(Unknown Source)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.everit.json.schema.loader.ObjectSchemaLoader.load(ObjectSchemaLoader.java:32)
	at org.everit.json.schema.loader.AbstractSchemaExtractor.buildObjectSchema(SchemaExtractor.java:113)
	at org.everit.json.schema.loader.TypeBasedSchemaExtractor.loadForExplicitType(SchemaExtractor.java:248)
	at org.everit.json.schema.loader.TypeBasedSchemaExtractor$$Lambda$152/405043958.apply(Unknown Source)
	at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:44)
	at org.everit.json.schema.loader.TypeBasedSchemaExtractor.extract(SchemaExtractor.java:217)
	at org.everit.json.schema.loader.AbstractSchemaExtractor.extract(SchemaExtractor.java:80)
	at org.everit.json.schema.loader.SchemaLoader.runSchemaExtractors(SchemaLoader.java:372)
	at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:340)
	at org.everit.json.schema.loader.SchemaLoader$$Lambda$136/2012654961.apply(Unknown Source)
	at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:44)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:410)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:262)
```

The code ends up in https://github.com/everit-org/json-schema/blob/master/core/src/main/java/org/everit/json/schema/loader/JsonPointerEvaluator.java#L158 . With this.fragment set to ```#OBJECT_REF``` and the document variable containing the correct schema. the ```tokens.poll()``` statement removed the only token from tokens, meaning there is no query to be executed and the entire document is returned. Instead, it should query by id, I would think

The JsonPointerEvaluator does not seem to have $id-based pointer lookup. Not sure if it should hit an entirely different code path altogether or if this code path is broken. Or if I'm making a mistake :)

I attached a screenshot with the debugger situation, including a watched variable set to manually retrieve the $id field from the definitions to show that it is present. Note that my IDE did not find the sources, so this is decompiled bytecode showing, but that should not matter.
<img width="1638" alt="screenshot 2018-11-19 at 22 24 11" src="https://user-images.githubusercontent.com/21126/48735933-0c20a080-ec4a-11e8-8d9c-d5e289eb0161.png">

**Comment by erosb** [comment]
Hello, thanks for investigating this. This $id lookup definitely doesn't work with pointers pointing to external json documents. I'm not actually sure if they should, according to the specification. I will read after it in detail later.

**Comment by erosb** [comment]
Hello, I looked into the current version of the specification, and [it says](http://json-schema.org/latest/json-schema-core.html#rfc.section.8.3.2):

> dereferencing a "$ref" reference involves first resolving its value as a URI reference against the current base URI per RFC 3986 [RFC3986].

> *If the resulting URI identifies a schema within the current document*, [...], then that schema SHOULD be used automatically.

So this kind of reference-by-id doesn't have to (shouldn't?) work with external schema documents. Closing this issue.
