### ISSUE TITLE
java.net.MalformedURLException: unknown protocol: classpath

### ISSUE THREAD

**Issue by parameshnalla** [everit-org/json-schema#281]
Hi Team,
I'm trying to use this library for my project. Maybe I'm missing something here looking for experienced
eyes to help me out.  

In my JSON schema, I'm trying to refer to another schema and trying to validate the JSON message using the library. 

Code:
```
InputStream inputStream  = ValidateJson.class.getResourceAsStream("/"+"remote-scheduler-delete-task.json");
    InputStream inputStream1  = ValidateJson.class.getResourceAsStream("/"+"delete-message.json");
    JSONObject inputMessage = new JSONObject(new JSONTokener(inputStream1));
    JSONObject rawSchema = new JSONObject(new JSONTokener(inputStream));


    SchemaLoader schemaLoader = SchemaLoader.builder()
            .schemaClient(SchemaClient.classPathAwareClient())
            .schemaJson(rawSchema)
            .resolutionScope("classpath://Users/pnalla/Projects_Latest/jsonToPojo/src/main/resources/") // setting the default resolution scope
            .build();

    schemaLoader.load().build().validate(inputMessage);
```

Error: 

```
Exception in thread "main" java.io.UncheckedIOException: java.net.MalformedURLException: unknown protocol: classpath
	at org.everit.json.schema.loader.internal.DefaultSchemaClient.get(DefaultSchemaClient.java:20)
	at org.everit.json.schema.loader.ClassPathAwareSchemaClient.lambda$get$0(ClassPathAwareSchemaClient.java:24)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.everit.json.schema.loader.ClassPathAwareSchemaClient.get(ClassPathAwareSchemaClient.java:24)
	at org.everit.json.schema.loader.JsonPointerEvaluator.executeWith(JsonPointerEvaluator.java:78)
	at org.everit.json.schema.loader.JsonPointerEvaluator.lambda$forURL$1(JsonPointerEvaluator.java:121)
	at org.everit.json.schema.loader.JsonPointerEvaluator.query(JsonPointerEvaluator.java:151)
	at org.everit.json.schema.loader.ReferenceLookup.lookup(ReferenceLookup.java:158)
	at org.everit.json.schema.loader.ReferenceSchemaExtractor.extract(SchemaExtractor.java:193)
	at org.everit.json.schema.loader.AbstractSchemaExtractor.extract(SchemaExtractor.java:113)
	at org.everit.json.schema.loader.SchemaLoader.runSchemaExtractors(SchemaLoader.java:384)
```

**Comment by erosb** [comment]
Hi!

The `/Users/pnalla/Projects_Latest/jsonToPojo/src/main/resources/` directory seems to be a classpath root directory, and not an absolute path within your classpath. My blind-guess without trying is setting the resolution scope to `classpath://` or `classpath:///` . 

If it doesn't work then please let me know about
 - the root schema (`rawSchemaJson`) you are using
 - and the relative location of the referred schemas under `src/main/resources`

Thanks.

**Comment by parameshnalla** [comment]
Issue resolved after using classpath as `classpath:/// `. Thank you @erosb.
