### ISSUE TITLE
$ref resolution without Spring framework

### ISSUE THREAD

**Issue by Mr-indescribable** [everit-org/json-schema#291]
Hi,

I'm tring to use the json-schema library in a web application that doesn't use Spring framework. And I encountered some problems about the "$ref".

------------------

Foreword: 

The version of json-schema that I'm using is the last release (1.11.1) downloaded from the releases page.

I've tried both "classpath://" and "classpath:///", and there is no difference between them.

------------------

### 1st. "no protocol"

I did something similar with what the doc in the README file.

* the Java code:

```java
String jschRoot = "/directory_in_classpath/to/store/json_files";
SchemaLoader schemaLoader = SchemaLoader.builder()
                .schemaClient(SchemaClient.classPathAwareClient())
                .resolutionScope("classpath://" + jschRoot)
                .build();

InputStream inStream = Test.class
                .getClassLoader()
                .getResourceAsStream(jschRoot + "/schema.json");

JSONObject rawSchema = new JSONObject(new JSONTokener(inStream));
Schema schema = schemaLoader.load(rawSchema);
schema.validate(aJsonObject);
```

* the JSON schema
```json
{
        "type" : "object",
        "properties" : {
                "something" : {"$ref" : "predefined.json" }
        }
}
```

* and the exception

```text
java.io.UncheckedIOException: java.net.MalformedURLException: no protocol: predefined.json
	at org.everit.json.schema.loader.internal.DefaultSchemaClient.get(DefaultSchemaClient.java:20)
	at org.everit.json.schema.loader.JsonPointerEvaluator.executeWith(JsonPointerEvaluator.java:78)
	at org.everit.json.schema.loader.JsonPointerEvaluator.lambda$forURL$1(JsonPointerEvaluator.java:121)
	at org.everit.json.schema.loader.JsonPointerEvaluator.query(JsonPointerEvaluator.java:151)
	at org.everit.json.schema.loader.ReferenceLookup.lookup(ReferenceLookup.java:173)
	at org.everit.json.schema.loader.ReferenceSchemaExtractor.extract(SchemaExtractor.java:193)
	at org.everit.json.schema.loader.AbstractSchemaExtractor.extract(SchemaExtractor.java:113)
	at org.everit.json.schema.loader.SchemaLoader.runSchemaExtractors(SchemaLoader.java:383)
	at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:360)
	at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:46)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:434)
	at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:438)
	at org.everit.json.schema.loader.ObjectSchemaLoader.addPropertySchemaDefinition(ObjectSchemaLoader.java:70)
	at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$populatePropertySchemas$9(ObjectSchemaLoader.java:64)
	at org.everit.json.schema.loader.JsonObject.iterateOnEntry(JsonObject.java:84)
	at org.everit.json.schema.loader.JsonObject.lambda$forEach$1(JsonObject.java:79)
	at java.util.HashMap$EntrySet.forEach(HashMap.java:1044)
	at org.everit.json.schema.loader.JsonObject.forEach(JsonObject.java:79)
	at org.everit.json.schema.loader.ObjectSchemaLoader.populatePropertySchemas(ObjectSchemaLoader.java:61)
	at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$load$0(ObjectSchemaLoader.java:32)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.everit.json.schema.loader.ObjectSchemaLoader.load(ObjectSchemaLoader.java:32)
	at org.everit.json.schema.loader.AbstractSchemaExtractor.buildObjectSchema(SchemaExtractor.java:138)
	at org.everit.json.schema.loader.TypeBasedSchemaExtractor.loadForExplicitType(SchemaExtractor.java:277)
	at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:46)
	at org.everit.json.schema.loader.TypeBasedSchemaExtractor.extract(SchemaExtractor.java:247)
	at org.everit.json.schema.loader.AbstractSchemaExtractor.extract(SchemaExtractor.java:113)
	at org.everit.json.schema.loader.SchemaLoader.runSchemaExtractors(SchemaLoader.java:396)
	at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:360)
	at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:46)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:434)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:281)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:264)
	at com.test.Test.main(Test.java:33)
Caused by: java.net.MalformedURLException: no protocol: predefined.json
	at java.net.URL.<init>(URL.java:593)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.everit.json.schema.loader.internal.DefaultSchemaClient.get(DefaultSchemaClient.java:18)
	... 33 more

```

According to the [README file](https://github.com/everit-org/json-schema#loading-from-the-classpath), the referred JSON file "predefined.json" should be found at "/directory_in_classpath/to/store/json_files/predefined.json" in the classpath. But, it didn't work as expected. Usually, if a file could not be found, something like "No such file or directory" should be thrown, seems it does not even pass the verification. And the same thing happened when I change the protocol form "classpath://" to "file://" as long as I'm using a relative path.

-------------------------------

### 2nd. "unknown protocol: classpath"

After encounterred the previous problem, I changed the value of "$ref" field in the JSON schema file from a relative path to a absolute path: "classpath://directory_in_classpath/to/store/json_files/predefined.json".

Then, that's another exception:

```text
java.io.UncheckedIOException: java.net.MalformedURLException: unknown protocol: classpath
	at org.everit.json.schema.loader.internal.DefaultSchemaClient.get(DefaultSchemaClient.java:20)
	at org.everit.json.schema.loader.JsonPointerEvaluator.executeWith(JsonPointerEvaluator.java:78)
	at org.everit.json.schema.loader.JsonPointerEvaluator.lambda$forURL$1(JsonPointerEvaluator.java:121)
	at org.everit.json.schema.loader.JsonPointerEvaluator.query(JsonPointerEvaluator.java:151)
	at org.everit.json.schema.loader.ReferenceLookup.lookup(ReferenceLookup.java:173)
	at org.everit.json.schema.loader.ReferenceSchemaExtractor.extract(SchemaExtractor.java:193)
	at org.everit.json.schema.loader.AbstractSchemaExtractor.extract(SchemaExtractor.java:113)
	at org.everit.json.schema.loader.SchemaLoader.runSchemaExtractors(SchemaLoader.java:383)
	at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:360)
	at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:46)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:434)
	at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:438)
	at org.everit.json.schema.loader.ObjectSchemaLoader.addPropertySchemaDefinition(ObjectSchemaLoader.java:70)
	at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$populatePropertySchemas$9(ObjectSchemaLoader.java:64)
	at org.everit.json.schema.loader.JsonObject.iterateOnEntry(JsonObject.java:84)
	at org.everit.json.schema.loader.JsonObject.lambda$forEach$1(JsonObject.java:79)
	at java.util.HashMap$EntrySet.forEach(HashMap.java:1044)
	at org.everit.json.schema.loader.JsonObject.forEach(JsonObject.java:79)
	at org.everit.json.schema.loader.ObjectSchemaLoader.populatePropertySchemas(ObjectSchemaLoader.java:61)
	at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$load$0(ObjectSchemaLoader.java:32)
	at java.util.Optional.ifPresent(Optional.java:159)
	at org.everit.json.schema.loader.ObjectSchemaLoader.load(ObjectSchemaLoader.java:32)
	at org.everit.json.schema.loader.AbstractSchemaExtractor.buildObjectSchema(SchemaExtractor.java:138)
	at org.everit.json.schema.loader.TypeBasedSchemaExtractor.loadForExplicitType(SchemaExtractor.java:277)
	at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:46)
	at org.everit.json.schema.loader.TypeBasedSchemaExtractor.extract(SchemaExtractor.java:247)
	at org.everit.json.schema.loader.AbstractSchemaExtractor.extract(SchemaExtractor.java:113)
	at org.everit.json.schema.loader.SchemaLoader.runSchemaExtractors(SchemaLoader.java:396)
	at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:360)
	at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:46)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:434)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:281)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:264)
	at com.test.Test.main(Test.java:33)
Caused by: java.net.MalformedURLException: unknown protocol: classpath
	at java.net.URL.<init>(URL.java:600)
	at java.net.URL.<init>(URL.java:490)
	at java.net.URL.<init>(URL.java:439)
	at org.everit.json.schema.loader.internal.DefaultSchemaClient.get(DefaultSchemaClient.java:18)
	... 33 more

```

--------------------

BTW, is there any additional documentation except javadoc? I tried to find more documentations but the only thing I've found is the javadoc.

**Comment by erosb** [comment]
Hello @Mr-indescribable , can you please submit a PR with a failing test reproducing your problem? Thanks.

**Comment by Mr-indescribable** [comment]
But why? I have already posted the code here, though they are fragments.

I think there could mostly be some kind of incorrect usage that caused these exceptions. If it was a "massive" bug, then there must be a lot of complains and I must found them through google search. Actually, I'm asking for some corrections. :smile:

**Comment by Mr-indescribable** [comment]
Well, seems a PR is not not suitable for this, I uploaded the complete test into my demo repository.

Follow this link to find it: [the demo](https://github.com/Mr-indescribable/demos/tree/master/everit-jschema-test)

---------------

You can reproduce the problem in a Linux box with JRE 1.8.

---------------

P.S. I recompiled the library (release 1.11.1) again and put it in the "lib" directory as well as its dependencies copied by:

```
mvn package dependency:copy-dependencies
```

**Comment by erosb** [comment]
Hi!

I couldn't find the `pom.xml` in your project so just guessing here, but probably found the problem:
Try this:
```java
InputStream inStream = Test.class
	.getClassLoader()
	.getResourceAsStream(jschRoot + "/schema.json");

JSONObject rawSchema = new JSONObject( new JSONTokener(inStream) );
SchemaLoader schemaLoader = SchemaLoader.builder()
	.schemaClient(SchemaClient.classPathAwareClient())
	.resolutionScope("classpath://" + jschRoot)
	.schemaJson(rawSchema)
	.build();

Schema schema = schemaLoader.load().build();
```

Explanation: the `load(rawSchema)` call that you used is actually a static method of the `SchemaLoader` class, not an instance method, so it doesn't use the configuration you set up on the instance. The `load()` method returning a `Schema.Builder` is the instance method you have to call so the loading will happen with the configuration you set up (I will try to make it more clear in the readme).

The static `load(rawSchema)`  method is left around mostly for compatibility reasons, this was the way how the very first version of the library was implemented, so we don't remove it, it just loads the schema with a pure configuration which is compatible with the 1.0.0 version (it isn't a very useful configuration though).

Documentation: I try to put as much into the README.md as I find it useful, but of course I'm not a user of the library, so I can't really tell what is missing. Feel free to ask. Javadoc-wise we are obviously lagging behind. Contributions are welcome. The thing is that this project is not sponsored actively by anyone so I just support it in my free time, which is more and more limited.

**Comment by Mr-indescribable** [comment]
Hi erosb,

That's just a mere demo so I didn't use maven on it.

------------

And thanks for your replay, but it not works at all.

Well, that's not something emergency, if you can't reproduce the problem, then just let it go :smile:

It's not necessary to waste your time on such a unreproducible problem and in that case, please don't close this issue, maybe I can meet someone that encountered the same problem. Thanks.

**Comment by erosb** [comment]
wait.. I can't see the `predefined.json` in your project. When I put an empty schema object (`{}`) to `com/test/predefined.json` then it loads the schema (with the ^above mentioned changes).

**Comment by Mr-indescribable** [comment]
Yeah, that file does not exist.

Actually, I have already did the test with that "predefined.json". No matter if it exists or not, the same exception is thrown. So I didn't put it in this demo. And usually, when a file is not found, the exception should be something like "No such file or directory" isn't it?

**Comment by Mr-indescribable** [comment]
Now I put the "predefined.json" into that demo, but it changes nothing.

**Comment by Mr-indescribable** [comment]
Oh, I figured it out.

I forgot to push the commit which I added at home, and now I'm using the old test code (without these changes you've provided).

Now it stops throwing "no protocol" with the predefined.json file and the change you provided.

--------------

But, another problem appears.

I've written the predefined.json like this:

```json
{
        "type": "integer",
        "requiresInteger": true
}
```

And I send the following json into the verification:

```json
{"a": "aa"}
```

And it just passes the verification. :confused:  Seems I didn't write the referred "predefined.json" in a right way.

Actually, I didn't understand the documentations about $ref resolution in the README file clearly. Could you please to show me an example about "how to use the referred JSON file" ?

**Comment by erosb** [comment]
Just to make things sure I pushed my working version to here: https://github.com/erosb/demos

**Comment by Mr-indescribable** [comment]
Got it :+1:

**Comment by Mr-indescribable** [comment]
Uh, I find that this project is an implementation of json-schema.org's JSON schema specification.

The doc I was searching for is in json-schema.org actually.
