### ISSUE TITLE
Reference Resolver parentScrope cannot be null, but cannot be set

### ISSUE THREAD

**Issue by jsteinich** [everit-org/json-schema#32]
ReferenceResolver requires a parent scope even when the reference is local to the current schema. Following the call stack back, the "id" field of SchemaLoader is being used for the parent scope. That can only be set from the "id" field of the SchemaLoaderBuilder, which isn't publicly available. Ideally, id wouldn't need to be set if only using local references.

**Comment by erosb** [comment]
Hello,

could you please provide some example of what doesn't work and how do you expect it to work? Preferably a schema json with a subject to be validated?

**Comment by jsteinich** [comment]
Here is an example schema that fails to load in correctly:
[brokenSchema.txt](https://github.com/everit-org/json-schema/files/205161/brokenSchema.txt)
It was taken from http://spacetelescope.github.io/understanding-json-schema/structuring.html

The code looks like:
`try (InputStream inputStream = getClass().getResourceAsStream("/path/to/your/schema.json")) {
  JSONObject rawSchema = new JSONObject(new JSONTokener(inputStream));
  SchemaLoader schemaLoader = SchemaLoader.builder().schemaJson(rawSchema).build();
  Schema schema = schemaLoader.load().build();
}`

It fails with this stack trace:
`Caused by: java.lang.NullPointerException: parentScope cannot be null
	at java.util.Objects.requireNonNull(Objects.java:228)
	at org.everit.json.schema.loader.internal.ReferenceResolver.<init>(ReferenceResolver.java:49)
	at org.everit.json.schema.loader.internal.ReferenceResolver.resolve(ReferenceResolver.java:41)
	at org.everit.json.schema.loader.SchemaLoader.lookupReference(SchemaLoader.java:515)
	at org.everit.json.schema.loader.SchemaLoader.buildSchemaWithoutExplicitType(SchemaLoader.java:382)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:464)
	at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:477)
	at org.everit.json.schema.loader.SchemaLoader.lambda$addPropertySchemaDefinition$5(SchemaLoader.java:279)
	at org.everit.json.schema.loader.SchemaLoader$$Lambda$21/425918570.accept(Unknown Source)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl.lambda$then$0(TypeBasedMultiplexer.java:79)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl$$Lambda$13/1285044316.accept(Unknown Source)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.orElse(TypeBasedMultiplexer.java:247)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.requireAny(TypeBasedMultiplexer.java:257)
	at org.everit.json.schema.loader.SchemaLoader.addPropertySchemaDefinition(SchemaLoader.java:281)
	at org.everit.json.schema.loader.SchemaLoader.lambda$populatePropertySchemas$16(SchemaLoader.java:540)
	at org.everit.json.schema.loader.SchemaLoader$$Lambda$20/517938326.accept(Unknown Source)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.everit.json.schema.loader.SchemaLoader.populatePropertySchemas(SchemaLoader.java:539)
	at org.everit.json.schema.loader.SchemaLoader.lambda$buildObjectSchema$9(SchemaLoader.java:348)
	at org.everit.json.schema.loader.SchemaLoader$$Lambda$12/1212899836.accept(Unknown Source)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl.lambda$then$0(TypeBasedMultiplexer.java:79)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl$$Lambda$13/1285044316.accept(Unknown Source)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.orElse(TypeBasedMultiplexer.java:247)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.requireAny(TypeBasedMultiplexer.java:257)
	at org.everit.json.schema.loader.SchemaLoader.buildObjectSchema(SchemaLoader.java:349)
	at org.everit.json.schema.loader.SchemaLoader.loadForExplicitType(SchemaLoader.java:495)
	at org.everit.json.schema.loader.SchemaLoader.loadForType(SchemaLoader.java:505)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:466)`

**Comment by erosb** [comment]
@jsteinich thanks, now it is clear for me, it will be fixed in the new release.
Until then you can use the older `SchemaLoader.load(rawJson)` method, without the builder.

**Comment by jsteinich** [comment]
Thanks. Any timeline for the next release? I'm also waiting for the fix for #30 to be released.

**Comment by erosb** [comment]
@jsteinich I've just uploaded a [release candidate](https://github.com/everit-org/json-schema/releases/tag/1.3.0-RC1) to github. Hopefully it fixes this issue. Could you please test it?

Thank you.

**Comment by jsteinich** [comment]
Looks to be fixed. I'm no longer getting errors and the references seem to be followed correctly.
Thanks

**Comment by erosb** [comment]
Thanks for your feedback. On the other hand I'm still a bit afraid of other usecases, I'd like to spend a few more days with this issue the final 1.3.0 release.

**Comment by erosb** [comment]
Ok, I've just tagged & released 1.3.0 on github, @balazs-zsoldos please release 1.3.0 on maven central.

**Comment by balazs-zsoldos** [comment]
1.3.0 is available on maven-central
