### ISSUE TITLE
org.everit.json.schema.SchemaException: key null: expected type is one of JSONObject, found: Boolean

### ISSUE THREAD

**Issue by rahilsh** [everit-org/json-schema#324]
I am trying to validate a schema using the latest meta schema but I am getting below error. I am using 1.5.1 of org.everit.json.schema.

```
Exception in thread "main" org.everit.json.schema.SchemaException: key null: expected type is one of JSONObject, found: Boolean
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.lambda$requireAny$1(TypeBasedMultiplexer.java:244)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.orElse(TypeBasedMultiplexer.java:233)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.requireAny(TypeBasedMultiplexer.java:243)
	at org.everit.json.schema.loader.ObjectSchemaLoader.addPropertySchemaDefinition(ObjectSchemaLoader.java:81)
	at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$populatePropertySchemas$3(ObjectSchemaLoader.java:70)
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948)
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580)
	at org.everit.json.schema.loader.ObjectSchemaLoader.populatePropertySchemas(ObjectSchemaLoader.java:69)
	at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$load$0(ObjectSchemaLoader.java:34)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl.lambda$then$0(TypeBasedMultiplexer.java:78)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.orElse(TypeBasedMultiplexer.java:233)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.requireAny(TypeBasedMultiplexer.java:243)
	at org.everit.json.schema.loader.ObjectSchemaLoader.load(ObjectSchemaLoader.java:35)
	at org.everit.json.schema.loader.SchemaLoader.buildObjectSchema(SchemaLoader.java:324)
	at org.everit.json.schema.loader.SchemaLoader.loadForExplicitType(SchemaLoader.java:317)
	at org.everit.json.schema.loader.SchemaLoader.buildAnyOfSchemaForMultipleTypes(SchemaLoader.java:228)
	at org.everit.json.schema.loader.SchemaLoader.loadForType(SchemaLoader.java:333)
	at org.everit.json.schema.loader.SchemaLoader.lambda$load$0(SchemaLoader.java:292)
	at java.util.Optional.orElseGet(Optional.java:267)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:288)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:178)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:163)
```

Sample code for reference

```
import org.everit.json.schema.Schema;
import org.everit.json.schema.loader.SchemaLoader;
import org.json.JSONObject;

public class JsonSchema {

  public static void main(String[] args) {
    Schema test =
        SchemaLoader.load(
            new JSONObject(
                "{\"$schema\":\"http://json-schema.org/draft-07/schema#\",\"$id\":\"http://json-schema.org/draft-07/schema#\",\"title\":\"Core schema meta-schema\",\"definitions\":{\"schemaArray\":{\"type\":\"array\",\"minItems\":1,\"items\":{\"$ref\":\"#\"}},\"nonNegativeInteger\":{\"type\":\"integer\",\"minimum\":0},\"nonNegativeIntegerDefault0\":{\"allOf\":[{\"$ref\":\"#/definitions/nonNegativeInteger\"},{\"default\":0}]},\"simpleTypes\":{\"enum\":[\"array\",\"boolean\",\"integer\",\"null\",\"number\",\"object\",\"string\"]},\"stringArray\":{\"type\":\"array\",\"items\":{\"type\":\"string\"},\"uniqueItems\":true,\"default\":[]}},\"type\":[\"object\",\"boolean\"],\"properties\":{\"$id\":{\"type\":\"string\",\"format\":\"uri-reference\"},\"$schema\":{\"type\":\"string\",\"format\":\"uri\"},\"$ref\":{\"type\":\"string\",\"format\":\"uri-reference\"},\"$comment\":{\"type\":\"string\"},\"title\":{\"type\":\"string\"},\"description\":{\"type\":\"string\"},\"default\":true,\"readOnly\":{\"type\":\"boolean\",\"default\":false},\"examples\":{\"type\":\"array\",\"items\":true},\"multipleOf\":{\"type\":\"number\",\"exclusiveMinimum\":0},\"maximum\":{\"type\":\"number\"},\"exclusiveMaximum\":{\"type\":\"number\"},\"minimum\":{\"type\":\"number\"},\"exclusiveMinimum\":{\"type\":\"number\"},\"maxLength\":{\"$ref\":\"#/definitions/nonNegativeInteger\"},\"minLength\":{\"$ref\":\"#/definitions/nonNegativeIntegerDefault0\"},\"pattern\":{\"type\":\"string\",\"format\":\"regex\"},\"additionalItems\":{\"$ref\":\"#\"},\"items\":{\"anyOf\":[{\"$ref\":\"#\"},{\"$ref\":\"#/definitions/schemaArray\"}],\"default\":true},\"maxItems\":{\"$ref\":\"#/definitions/nonNegativeInteger\"},\"minItems\":{\"$ref\":\"#/definitions/nonNegativeIntegerDefault0\"},\"uniqueItems\":{\"type\":\"boolean\",\"default\":false},\"contains\":{\"$ref\":\"#\"},\"maxProperties\":{\"$ref\":\"#/definitions/nonNegativeInteger\"},\"minProperties\":{\"$ref\":\"#/definitions/nonNegativeIntegerDefault0\"},\"required\":{\"$ref\":\"#/definitions/stringArray\"},\"additionalProperties\":{\"$ref\":\"#\"},\"definitions\":{\"type\":\"object\",\"additionalProperties\":{\"$ref\":\"#\"},\"default\":{}},\"properties\":{\"type\":\"object\",\"additionalProperties\":{\"$ref\":\"#\"},\"default\":{}},\"patternProperties\":{\"type\":\"object\",\"additionalProperties\":{\"$ref\":\"#\"},\"propertyNames\":{\"format\":\"regex\"},\"default\":{}},\"dependencies\":{\"type\":\"object\",\"additionalProperties\":{\"anyOf\":[{\"$ref\":\"#\"},{\"$ref\":\"#/definitions/stringArray\"}]}},\"propertyNames\":{\"$ref\":\"#\"},\"const\":true,\"enum\":{\"type\":\"array\",\"items\":true,\"minItems\":1,\"uniqueItems\":true},\"type\":{\"anyOf\":[{\"$ref\":\"#/definitions/simpleTypes\"},{\"type\":\"array\",\"items\":{\"$ref\":\"#/definitions/simpleTypes\"},\"minItems\":1,\"uniqueItems\":true}]},\"format\":{\"type\":\"string\"},\"contentMediaType\":{\"type\":\"string\"},\"contentEncoding\":{\"type\":\"string\"},\"if\":{\"$ref\":\"#\"},\"then\":{\"$ref\":\"#\"},\"else\":{\"$ref\":\"#\"},\"allOf\":{\"$ref\":\"#/definitions/schemaArray\"},\"anyOf\":{\"$ref\":\"#/definitions/schemaArray\"},\"oneOf\":{\"$ref\":\"#/definitions/schemaArray\"},\"not\":{\"$ref\":\"#\"}},\"default\":true}"));
    test.validate(
        new JSONObject(
            "{\"$schema\":\"http://json-schema.org/draft-07/schema#\",\"title\":\"User\",\"description\":\"test\",\"type\":\"object\",\"properties\":{\"id\":{\"type\":\"integer\"},\"name\":{\"type\":\"string\"}},\"required\":[\"id\",\"name\"]}"));
  }
}
```

**Comment by erosb** [comment]
Hello, is this reproducible with the latest version? It is 1.11.1 (version 1.5.1 is 2.5 years old, by the way).

**Comment by rahilsh** [comment]
oh! Maven central repo(https://mvnrepository.com/artifact/org.everit.json/org.everit.json.schema) shows 1.5.1 as the latest. When I add 1.11.1 in pom, maven is not able to resolve it.

**Comment by erosb** [comment]
Please refer to the [Maven installation](https://github.com/everit-org/json-schema#maven-installation) section of the manual (you have to add the JitPack repository).

**Comment by rahilsh** [comment]
@erosb Thanks a lot
BTW its there on maven repo too(https://mvnrepository.com/artifact/com.github.everit-org.json-schema/org.everit.json.schema)

**Comment by rahilsh** [comment]
getting a different error now

```
Exception in thread "main" java.lang.NoClassDefFoundError: com/damnhandy/uri/template/MalformedUriTemplateException
	at org.everit.json.schema.loader.SpecificationVersion.<clinit>(SpecificationVersion.java:141)
	at org.everit.json.schema.loader.SchemaLoader$SchemaLoaderBuilder.<init>(SchemaLoader.java:76)
	at org.everit.json.schema.loader.SchemaLoader.builder(SchemaLoader.java:252)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:277)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:264)
	at in.r.util.json.JsonValidator.main(JsonValidator.java:12)
Caused by: java.lang.ClassNotFoundException: com.damnhandy.uri.template.MalformedUriTemplateException
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 6 more
```

**Comment by rahilsh** [comment]
Adding the repository as https://jitpack.io works. The ClassNotFoundException error is thrown by the 1.11.1 of maven(https://mvnrepository.com/artifact/com.github.everit-org.json-schema/org.everit.json.schema)

**Comment by erosb** [comment]
closing ticket - not reproducible

**Comment by ghYura** [comment]
@rahilsh How did you handle java.lang.NoClassDefFoundError: com/damnhandy/uri/template/MalformedUriTemplateException ?

**Comment by erosb** [comment]
@ghYura please check if this dependency is not excluded (or omitted for conflict) in your pom: `com.damnhandy:handy-uri-templates:2.1.8`. It is [present in the pom.xml](https://github.com/everit-org/json-schema/blob/master/core/pom.xml#L265) so if the class is missing then it should be an issue with your dependency configuration.

**Comment by ghYura** [comment]
@erosb Thank you! Helped
