### ISSUE TITLE
allOf keyword resolve problem 

### ISSUE THREAD

**Issue by rernas35** [everit-org/json-schema#35]
Hi , 

I have json schema attached which includes "allOf" keyword and I am facing the following error for the attached request .  Does the library support allOf keyword ? 

org.everit.json.schema.ValidationException: #/CARDConfirmCashAdvanceWithInstallmentCompositionRequest/Body: #: only 0 subschema matches out of 2
	at org.everit.json.schema.ValidationException.prepend(ValidationException.java:214)
	at org.everit.json.schema.ValidationException.prepend(ValidationException.java:193)
	at org.everit.json.schema.ObjectSchema.lambda$testProperties$7(ObjectSchema.java:322)
	at java.util.Optional.map(Optional.java:215)
	at org.everit.json.schema.ObjectSchema.testProperties(ObjectSchema.java:322)
	at org.everit.json.schema.ObjectSchema.validate(ObjectSchema.java:384)
	at 

[request.txt](https://github.com/everit-org/json-schema/files/289235/request.txt)
[jsonschema.txt](https://github.com/everit-org/json-schema/files/289234/jsonschema.txt)

**Comment by erosb** [comment]
The library does support the allOf keyword. I will look deeper into this example when I'm back from my holiday.

**Comment by erosb** [comment]
I couldn't reproduce the issue. I created an integration test [here](https://github.com/everit-org/json-schema/commit/5a872bc994299e42d226fa08e426fbdbaccc8fb9) with the files you provided and it successfully passed the validation without any exceptions.
