### ISSUE TITLE
Json validator not working with array and type object

### ISSUE THREAD

**Issue by NicolaSpreafico** [everit-org/json-schema#42]
Hello,
I'm the user that is using the Java6 backport library re-compiled for Java7
http://stackoverflow.com/a/38345475/1013317

I found the problem and I cannot tell if the problem is related to the backport or it is even in the main library.

I have this schema
```
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"additionalProperties": false,
	"properties": {
		"organizations": {
			"type": "array",
			"additionalProperties": false,
			"items": {
				"type": "object",
				"properties": {
					"name": {
						"type": "string"
					},
					"title": {
						"type": "string"
					},
					"department": {
						"type": "string"
					}
				}
			}
		}
	}
}
```
and this json
```
{
    "organizations": [
        {
            "name": "name",
            "title": "title",        
            "department": "department"
        }
    ]
}
```
and the code
```
try {
    // Read the schema into json
    JSONObject rawSchema = new JSONObject(new JSONTokener(schemaStream));

    // Load the schema
    Schema schema = SchemaLoader.load(rawSchema);

    // throws a ValidationException if this object is invalid
    schema.validate(json);
} catch (JSONException | ValidationException e) {
    throw new FailedOperationException(e);
}
```
I used different online tools to test the validation and they all give a pass for correct json

But with the library I get the following error:
```
Caused by: org.everit.json.schema.ValidationException: extraneous key [title] is not permitted
	at org.everit.json.schema.ObjectSchema.failure(ObjectSchema.java:210)
	at org.everit.json.schema.ObjectSchema.testAdditionalProperties(ObjectSchema.java:268)
	at org.everit.json.schema.ObjectSchema.validate(ObjectSchema.java:379)
	at org.everit.json.schema.ArraySchema.testItems(ArraySchema.java:199)
	at org.everit.json.schema.ArraySchema.validate(ArraySchema.java:246)
	at org.everit.json.schema.ObjectSchema.testProperties(ObjectSchema.java:304)
	at org.everit.json.schema.ObjectSchema.validate(ObjectSchema.java:377)
	at it.noovle.ape.project.tools.json.schema.SchemaValidator.validate(SchemaValidator.java:37)
	... 50 more
```

Considering that the online tools are correct I can consider my schema as correct, so I'm wondering if there is a problem with the library itself or only the java6 backport version.

Regards

**Comment by NicolaSpreafico** [comment]
Found the problem, the `"additionalProperties": false`, property was misplaced
