### ISSUE TITLE
Relative path does not work when importing schema from another file using $ref

### ISSUE THREAD

**Issue by mejuhi** [everit-org/json-schema#438]
I have a use case where I have two schema files schema1.json and schema2.json. Both of these schema files reside in folder path /fold1/fold2

In schema1.json, I am trying to import schema definition from schema2.json

In schema1.json while using following syntax  it works fine:
 `"MsgHeader": { "$ref": "file:/fold1/fold2/schema2.json#/definitions/MsgHeaderType" },`
 
but I would like it to use relative path for eg like this:
  `"MsgHeader": { "$ref": "file:schema2.json#/definitions/MsgHeaderType" },`

since both the schema are in same folder, it should be able to identify and import. but it throws file not found exception

Is this feature not supported? or I am missing something?

**Comment by erosb** [comment]
Hello, please read the [$ref resolution](https://github.com/everit-org/json-schema#ref-resolution) section of the README.

**Comment by mejuhi** [comment]
Hello @erosb the setting you have suggested works for resolution of files in the classpath, in my use case all the schemas are stored outside in file system (not in classpath/jar).

In java code made following changes:
```
SchemaLoader loader = SchemaLoader.builder()
        .schemaClient(SchemaClient.classPathAwareClient())
        .schemaJson(new JSONObject(new JSONTokener(jsonSchema)))
        .resolutionScope("file:/fold1/fold2/") 
        .build();
srcSchema = loader.load().build();
// Validate json
srcSchema.validate(new JSONObject(data));
```

and in schema trying to refer like this:
```
"MsgHeader": { "$ref": "file:schema2.json#/definitions/MsgHeaderType" },
```

but it is still not able to find the correct path and tries to find the file in the root folder `'/'`

**Comment by erosb** [comment]
I suggest trying with real URLs like `file://schema2.json/...` (mind the `://`)

**Comment by mejuhi** [comment]
Okay, I tried with following changes:

on the json schema file made following change:
```
"MsgHeader": { "$ref": "file://MessageHeaderCopy.json#/definitions/MsgHeaderType" },
```
with java code as is:
```
SchemaLoader loader = SchemaLoader.builder()
        .schemaClient(SchemaClient.classPathAwareClient())
        .schemaJson(new JSONObject(new JSONTokener(jsonSchema)))
        .resolutionScope("file:/fold1/fold2/") 
        .build();
srcSchema = loader.load().build();
// Validate json
srcSchema.validate(new JSONObject(data));

```


but got the following exception
```
java.io.UncheckedIOException: java.net.UnknownHostException: schema2.json           
 at org.everit.json.schema.loader.internal.DefaultSchemaClient.get(DefaultSchemaClient.java:27)        
 at org.everit.json.schema.loader.ClassPathAwareSchemaClient.get(ClassPathAwareSchemaClient.java:33)            
 at org.everit.json.schema.loader.JsonPointerEvaluator.executeWith(JsonPointerEvaluator.java:80)         
 at org.everit.json.schema.loader.JsonPointerEvaluator.lambda$forURL$1(JsonPointerEvaluator.java:121)           
 at org.everit.json.schema.loader.JsonPointerEvaluator.query(JsonPointerEvaluator.java:151)             
 at org.everit.json.schema.loader.ReferenceLookup.lookup(ReferenceLookup.java:149)             
 at org.everit.json.schema.loader.ReferenceSchemaExtractor.extract(SchemaExtractor.java:193)            
 at org.everit.json.schema.loader.AbstractSchemaExtractor.extract(SchemaExtractor.java:113)           
 at org.everit.json.schema.loader.SchemaLoader.runSchemaExtractors(SchemaLoader.java:411)               
 at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:388)        
 at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:46)           
 at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:462)              
 at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:466)        
 at org.everit.json.schema.loader.ObjectSchemaLoader.addPropertySchemaDefinition(ObjectSchemaLoader.java:70)            
 at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$populatePropertySchemas$9(ObjectSchemaLoader.java:64)               at org.everit.json.schema.loader.JsonObject.iterateOnEntry(JsonObject.java:84)         
 at org.everit.json.schema.loader.JsonObject.lambda$forEach$1(JsonObject.java:79)              
 at java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1130)             
 at org.everit.json.schema.loader.JsonObject.forEach(JsonObject.java:79)              
 at org.everit.json.schema.loader.ObjectSchemaLoader.populatePropertySchemas(ObjectSchemaLoader.java:61)        
 at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$load$0(ObjectSchemaLoader.java:32)         
 at java.base/java.util.Optional.ifPresent(Optional.java:176)           
 at org.everit.json.schema.loader.ObjectSchemaLoader.load(ObjectSchemaLoader.java:32)           
 at org.everit.json.schema.loader.AbstractSchemaExtractor.buildObjectSchema(SchemaExtractor.java:138)          
 at org.everit.json.schema.loader.TypeBasedSchemaExtractor.loadForExplicitType(SchemaExtractor.java:277)        
 at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:46)          
 at org.everit.json.schema.loader.TypeBasedSchemaExtractor.extract(SchemaExtractor.java:247)            
 at org.everit.json.schema.loader.AbstractSchemaExtractor.extract(SchemaExtractor.java:113)            
 at org.everit.json.schema.loader.SchemaLoader.runSchemaExtractors(SchemaLoader.java:424)               
 at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:388)         
 at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:46)           
 at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:462)
```

**Comment by erosb** [comment]
> resolutionScope("file:/fold1/fold2/") 

This is still not correct.

**Comment by mejuhi** [comment]
hello @erosb 

tried these combinations:

1.
with java code as:
```
Schema srcSchema;
                SchemaLoader loader = SchemaLoader.builder()
        .schemaClient(SchemaClient.classPathAwareClient())
        .schemaJson(new JSONObject(new JSONTokener(jsonSchema)))
        .resolutionScope("file://fold1/fold2/") // setting the default resolution scope
        .build();

srcSchema = loader.load().build();
srcSchema.validate(new JSONObject(data));
```
and json ref as :
```
"MsgHeader": { "$ref": "file://MessageHeaderCopy.json#/definitions/MsgHeaderType" },
```

gives following exception:
```
java.io.UncheckedIOException: java.net.UnknownHostException: MessageHeaderCopy.json            
at org.everit.json.schema.loader.internal.DefaultSchemaClient.get(DefaultSchemaClient.java:27)          
at org.everit.json.schema.loader.ClassPathAwareSchemaClient.get(ClassPathAwareSchemaClient.java:33)            
at org.everit.json.schema.loader.JsonPointerEvaluator.executeWith(JsonPointerEvaluator.java:80)         
at org.everit.json.schema.loader.JsonPointerEvaluator.lambda$forURL$1(JsonPointerEvaluator.java:121)           
at org.everit.json.schema.loader.JsonPointerEvaluator.query(JsonPointerEvaluator.java:151)              
at org.everit.json.schema.loader.ReferenceLookup.lookup(ReferenceLookup.java:149)              
at org.everit.json.schema.loader.ReferenceSchemaExtractor.extract(SchemaExtractor.java:193)             
at org.everit.json.schema.loader.AbstractSchemaExtractor.extract(SchemaExtractor.java:113)             
at org.everit.json.schema.loader.SchemaLoader.runSchemaExtractors(SchemaLoader.java:411)                
at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:388)          
at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:46)            
at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:462)               
at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:466)         
at org.everit.json.schema.loader.ObjectSchemaLoader.addPropertySchemaDefinition(ObjectSchemaLoader.java:70)             
at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$populatePropertySchemas$9(ObjectSchemaLoader.java:64)               
at org.everit.json.schema.loader.JsonObject.iterateOnEntry(JsonObject.java:84)          
at org.everit.json.schema.loader.JsonObject.lambda$forEach$1(JsonObject.java:79)               
at java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1130)              
at org.everit.json.schema.loader.JsonObject.forEach(JsonObject.java:79)                
at org.everit.json.schema.loader.ObjectSchemaLoader.populatePropertySchemas(ObjectSchemaLoader.java:61)         
at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$load$0(ObjectSchemaLoader.java:32)          
at java.base/java.util.Optional.ifPresent(Optional.java:176)            at org.everit.json.schema.loader.ObjectSchemaLoader.load(ObjectSchemaLoader.java:32)            
at org.everit.json.schema.loader.AbstractSchemaExtractor.buildObjectSchema(SchemaExtractor.java:138)           
at org.everit.json.schema.loader.TypeBasedSchemaExtractor.loadForExplicitType(SchemaExtractor.java:277)         
at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:46)           
at org.everit.json.schema.loader.TypeBasedSchemaExtractor.extract(SchemaExtractor.java:247)             
at org.everit.json.schema.loader.AbstractSchemaExtractor.extract(SchemaExtractor.java:113)             
at org.everit.json.schema.loader.SchemaLoader.runSchemaExtractors(SchemaLoader.java:424)                
at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:388)          
at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:46)            
at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:462)

```

2.
with java code as:
```
Schema srcSchema;
SchemaLoader loader = SchemaLoader.builder()
        .schemaClient(SchemaClient.classPathAwareClient())
        .schemaJson(new JSONObject(new JSONTokener(jsonSchema)))
        .resolutionScope("classpath://fold1/fold2/") // setting the default resolution scope
        .build();

srcSchema = loader.load().build();
srcSchema.validate(new JSONObject(data));
```

and json ref as :
```
"MsgHeader": { "$ref": "file://MessageHeaderCopy.json#/definitions/MsgHeaderType" },
```
gives following exception:
```
java.io.UncheckedIOException: java.net.UnknownHostException: MessageHeaderCopy.json            
at org.everit.json.schema.loader.internal.DefaultSchemaClient.get(DefaultSchemaClient.java:27)          
at org.everit.json.schema.loader.ClassPathAwareSchemaClient.get(ClassPathAwareSchemaClient.java:33)            
at org.everit.json.schema.loader.JsonPointerEvaluator.executeWith(JsonPointerEvaluator.java:80)         
at org.everit.json.schema.loader.JsonPointerEvaluator.lambda$forURL$1(JsonPointerEvaluator.java:121)           
at org.everit.json.schema.loader.JsonPointerEvaluator.query(JsonPointerEvaluator.java:151)              
at org.everit.json.schema.loader.ReferenceLookup.lookup(ReferenceLookup.java:149)              
at org.everit.json.schema.loader.ReferenceSchemaExtractor.extract(SchemaExtractor.java:193)             
at org.everit.json.schema.loader.AbstractSchemaExtractor.extract(SchemaExtractor.java:113)             
at org.everit.json.schema.loader.SchemaLoader.runSchemaExtractors(SchemaLoader.java:411)                
at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:388)          
at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:46)            
at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:462)               
at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:466)         
at org.everit.json.schema.loader.ObjectSchemaLoader.addPropertySchemaDefinition(ObjectSchemaLoader.java:70)             
at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$populatePropertySchemas$9(ObjectSchemaLoader.java:64)               
at org.everit.json.schema.loader.JsonObject.iterateOnEntry(JsonObject.java:84)          
at org.everit.json.schema.loader.JsonObject.lambda$forEach$1(JsonObject.java:79)               
at java.base/java.util.HashMap$EntrySet.forEach(HashMap.java:1130)              
at org.everit.json.schema.loader.JsonObject.forEach(JsonObject.java:79)                
at org.everit.json.schema.loader.ObjectSchemaLoader.populatePropertySchemas(ObjectSchemaLoader.java:61)         
at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$load$0(ObjectSchemaLoader.java:32)          at java.base/java.util.Optional.ifPresent(Optional.java:176)            
at org.everit.json.schema.loader.ObjectSchemaLoader.load(ObjectSchemaLoader.java:32)            
at org.everit.json.schema.loader.AbstractSchemaExtractor.buildObjectSchema(SchemaExtractor.java:138)           
at org.everit.json.schema.loader.TypeBasedSchemaExtractor.loadForExplicitType(SchemaExtractor.java:277)         
at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:46)           
at org.everit.json.schema.loader.TypeBasedSchemaExtractor.extract(SchemaExtractor.java:247)             
at org.everit.json.schema.loader.AbstractSchemaExtractor.extract(SchemaExtractor.java:113)             
at org.everit.json.schema.loader.SchemaLoader.runSchemaExtractors(SchemaLoader.java:424)                
at org.everit.json.schema.loader.SchemaLoader.loadSchemaObject(SchemaLoader.java:388)          
at org.everit.json.schema.loader.JsonValue$Multiplexer.requireAny(JsonValue.java:46)            
at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:462)
```

**Comment by erosb** [comment]
your latest code snippet is broken at least at the following places:

> .resolutionScope("classpath://fold1/fold2/")

why classpath protocol? you want to load from the filesystem, don't you?
Also, if it is a unix file path, the path starts with a `/` , so the resolution scope should look something like `file:///fold1/fold2/` (mind the triple slash).

>  "$ref": "file://MessageHeaderCopy.json#/definitions/MsgHeaderType" 

this is an absolute URL therefore it won't be resolved against the initial resolution scope.

**Comment by mejuhi** [comment]
Yeah, i did realize `classpath` was not a right option to try.
I did try changing the resolution path (and yes you are right it was in the root folder (my miss)):
```
Schema cschema = SchemaLoader.builder()
	.schemaJson(new JSONObject(new JSONTokener(jsonSchema)))
    .resolutionScope("file:///fold1/fold2/")
	.build()
	.load().build();

```

but i still didnt understand what you meant by this:

> "$ref": "file://MessageHeaderCopy.json#/definitions/MsgHeaderType"
> this is an absolute URL therefore it won't be resolved against the initial resolution scope.

What should be the value in the json schema file to refer a file in `/fold1/fold2/`

**Comment by erosb** [comment]
If your initial resolution scope is `"file:///fold1/fold2/"` then a `"$ref": "MessageHeaderCopy.json"` will be resolved to `file:///fold1/fold2/MessageHeaderCopy.json`, because the $ref is relative (I think this is what you are looking for). But if you use an absolute $ref like `file:///MessageHeaderCopy.json` then it won't be resolved against anything, since it is already absolute.

**Comment by mejuhi** [comment]
Yeah, understood, I made the changes you suggested and it works as expected!
Thanks a lot for helping!
