### ISSUE TITLE
Implement Validator with Lenient mode in Groovy

### ISSUE THREAD

**Issue by mirpedrol** [everit-org/json-schema#463]
Hi! 

I am trying to use the Lenient mode of the validator in a Groovy script. The objective is to allow numbers to be validated as strings without failing. This is how the code with the default validator looks like:
```
import org.everit.json.schema.Schema
import org.everit.json.schema.loader.SchemaLoader
import org.everit.json.schema.ValidationException
import org.json.JSONObject
import org.json.JSONTokener
import org.json.JSONArray
import groovy.json.JsonSlurper
import groovy.json.JsonBuilder

class NfcoreSchema {

    public static void validateParameters(params, schema_filename) {

        // Validate parameters against the schema
        JSONObject raw_schema = new JSONObject(new JSONTokener(schema_filename))
        Schema schema = SchemaLoader.load(raw_schema)

        // Convert to JSONObject
        def jsonParams = new JsonBuilder(params)
        JSONObject params_json = new JSONObject(jsonParams.toString())

        // Validate
        try {
            schema.validate(params_json)
        } catch (ValidationException e) {
            JSONObject exceptionJSON = e.toJSON()
            printExceptions(exceptionJSON, params_json, log, enums)
        }
```

When I try to build a new validator method following the example in [the docs](https://github.com/everit-org/json-schema#lenient-mode) I get the following error:
` BUG! exception in phase 'semantic analysis' in source unit 'Script_c4c27e74' The lookup for WorkflowMain caused a failed compilation. There should not have been any compilation from this call.`
This is the full traceback
```
org.codehaus.groovy.GroovyBugError: BUG! exception in phase 'semantic analysis' in source unit 'Script_c4c27e74' The lookup for WorkflowMain caused a failed compilation. There should not have been any compilation from this call.
	at org.codehaus.groovy.control.ClassNodeResolver.findByClassLoading(ClassNodeResolver.java:214)
	at org.codehaus.groovy.control.ClassNodeResolver.tryAsLoaderClassOrScript(ClassNodeResolver.java:198)
	at org.codehaus.groovy.control.ClassNodeResolver.findClassNode(ClassNodeResolver.java:169)
	at org.codehaus.groovy.control.ClassNodeResolver.resolveName(ClassNodeResolver.java:125)
	at org.codehaus.groovy.control.ResolveVisitor.resolveToOuter(ResolveVisitor.java:870)
	at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:506)
	at org.codehaus.groovy.control.ResolveVisitor.resolve(ResolveVisitor.java:468)
	at org.codehaus.groovy.control.ResolveVisitor.transformVariableExpression(ResolveVisitor.java:1132)
	at org.codehaus.groovy.control.ResolveVisitor.transform(ResolveVisitor.java:889)
	at org.codehaus.groovy.control.ResolveVisitor.transformMethodCallExpression(ResolveVisitor.java:1277)
	at org.codehaus.groovy.control.ResolveVisitor.transform(ResolveVisitor.java:897)
	at org.codehaus.groovy.control.ResolveVisitor.transformBinaryExpression(ResolveVisitor.java:1207)
	at org.codehaus.groovy.control.ResolveVisitor.transform(ResolveVisitor.java:895)
	at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitExpressionStatement(ClassCodeExpressionTransformer.java:108)
	at org.codehaus.groovy.ast.stmt.ExpressionStatement.visit(ExpressionStatement.java:40)
	at org.codehaus.groovy.ast.CodeVisitorSupport.visitBlockStatement(CodeVisitorSupport.java:86)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitBlockStatement(ClassCodeVisitorSupport.java:164)
	at org.codehaus.groovy.control.ResolveVisitor.visitBlockStatement(ResolveVisitor.java:1569)
	at org.codehaus.groovy.ast.stmt.BlockStatement.visit(BlockStatement.java:69)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClassCodeContainer(ClassCodeVisitorSupport.java:138)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitConstructorOrMethod(ClassCodeVisitorSupport.java:111)
	at org.codehaus.groovy.ast.ClassCodeExpressionTransformer.visitConstructorOrMethod(ClassCodeExpressionTransformer.java:66)
	at org.codehaus.groovy.control.ResolveVisitor.visitConstructorOrMethod(ResolveVisitor.java:294)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitMethod(ClassCodeVisitorSupport.java:106)
	at org.codehaus.groovy.ast.ClassNode.visitMethods(ClassNode.java:1099)
	at org.codehaus.groovy.ast.ClassNode.visitContents(ClassNode.java:1092)
	at org.codehaus.groovy.ast.ClassCodeVisitorSupport.visitClass(ClassCodeVisitorSupport.java:52)
	at org.codehaus.groovy.control.ResolveVisitor.visitClass(ResolveVisitor.java:1486)
	at org.codehaus.groovy.control.ResolveVisitor.startResolving(ResolveVisitor.java:262)
	at org.codehaus.groovy.control.CompilationUnit.lambda$new$16(CompilationUnit.java:738)
	at org.codehaus.groovy.control.CompilationUnit$ISourceUnitOperation.doPhaseOperation(CompilationUnit.java:901)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:627)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
	at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
	at groovy.lang.GroovyShell.parseClass(GroovyShell.java:526)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:538)
	at groovy.lang.GroovyShell.parse(GroovyShell.java:570)
	at nextflow.script.ScriptParser.parse(ScriptParser.groovy:172)
	at nextflow.script.ScriptParser.parse(ScriptParser.groovy:191)
	at nextflow.script.ScriptParser.parse(ScriptParser.groovy:196)
	at nextflow.script.ScriptRunner.parseScript(ScriptRunner.groovy:198)
	at nextflow.script.ScriptRunner.execute(ScriptRunner.groovy:118)
	at nextflow.cli.CmdRun.run(CmdRun.groovy:308)
	at nextflow.cli.Launcher.run(Launcher.groovy:480)
	at nextflow.cli.Launcher.main(Launcher.groovy:639)
Caused by: org.codehaus.groovy.control.MultipleCompilationErrorsException: startup failed:
file:/Users/julia/Documents/NF-core/nf-core_sarek/lib/NfcoreSchema.groovy: 162: Apparent variable 'PrimitiveValidationStrategy' was found in a static scope but doesn't refer to a local variable, static field or class. Possible causes:
You attempted to reference a variable in the binding or an instance variable from a static context.
You misspelled a classname or statically imported field. Please check the spelling.
You attempted to use a method 'PrimitiveValidationStrategy' but left out brackets in a place not allowed by the grammar.
 @ line 162, column 80.
   .primitiveValidationStrategry(PrimitiveV
                                 ^

1 error

	at org.codehaus.groovy.control.ErrorCollector.failIfErrors(ErrorCollector.java:295)
	at org.codehaus.groovy.control.CompilationUnit$IPrimaryClassNodeOperation.doPhaseOperation(CompilationUnit.java:984)
	at org.codehaus.groovy.control.CompilationUnit.processPhaseOperations(CompilationUnit.java:671)
	at org.codehaus.groovy.control.CompilationUnit.compile(CompilationUnit.java:635)
	at groovy.lang.GroovyClassLoader.doParseClass(GroovyClassLoader.java:389)
	at groovy.lang.GroovyClassLoader.lambda$parseClass$3(GroovyClassLoader.java:332)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.compute(StampedCommonCache.java:163)
	at org.codehaus.groovy.runtime.memoize.StampedCommonCache.getAndPut(StampedCommonCache.java:154)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:330)
	at groovy.lang.GroovyClassLoader.parseClass(GroovyClassLoader.java:314)
	at groovy.lang.GroovyClassLoader.recompile(GroovyClassLoader.java:954)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:910)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:979)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:575)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:869)
	at groovy.lang.GroovyClassLoader.loadClass(GroovyClassLoader.java:745)
	at org.codehaus.groovy.control.ClassNodeResolver.findByClassLoading(ClassNodeResolver.java:209)
	... 47 common frames omitted

```

Which would be the correct way to implement that?

Thank you very much for your help!

**Comment by erosb** [comment]
The exception is specific to groovy and isn't thrown by the library, so I can't help with this. Also you don't enable the lenient mode in the sample java code you shared.

**Comment by mirpedrol** [comment]
Hi @erosb, thanks for your answer!

I am adding a new validator in the code to enable lenient mode, sorry for the confusion. 

```groovy
import org.everit.json.schema.Schema
import org.everit.json.schema.loader.SchemaLoader
import org.everit.json.schema.ValidationException
import org.json.JSONObject
import org.json.JSONTokener
import org.json.JSONArray
import groovy.json.JsonSlurper
import groovy.json.JsonBuilder

class NfcoreSchema {

    public static void validateParameters(params, schema_filename) {

        // Validate parameters against the schema
        JSONObject raw_schema = new JSONObject(new JSONTokener(schema_filename))
        Schema schema = SchemaLoader.load(raw_schema)

        // Convert to JSONObject
        def jsonParams = new JsonBuilder(params)
        JSONObject params_json = new JSONObject(jsonParams.toString())

        Validator validator = Validator.builder().primitiveValidationStrategry(PrimitiveValidationStrategy.LENIENT).build();

        // Validate
        try {
            schema.validate(params_json)
        } catch (ValidationException e) {
            JSONObject exceptionJSON = e.toJSON()
            printExceptions(exceptionJSON, params_json, log, enums)
        }
    }
}
```

**Comment by erosb** [comment]
What are the schema and the json instance that you are testing with?

**Comment by mirpedrol** [comment]
Here is the [schema](https://github.com/maxulysse/nf-core_sarek/blob/dev_number_validation/nextflow_schema.json) that I am trying and the params file 
[json_params.txt](https://github.com/everit-org/json-schema/files/9249380/json_params.txt)

**Comment by mirpedrol** [comment]
As one of the messages from the traceback is: `Apparent variable 'PrimitiveValidationStrategy' was found in a static scope but doesn't refer to a local variable, static field or class`
I was wondering if I am declaring the new validator in the correct scope, or if I am missing an import?

**Comment by erosb** [comment]
I think you just have to `import org.everit.json.schema.PrimitiveValidationStrategy`

**Comment by mirpedrol** [comment]
With this import I get the error `unable to resolve class org.everit.json.schema.PrimitiveValidationStrategy`

**Comment by erosb** [comment]
Please check if you use the right version of the library.

**Comment by mirpedrol** [comment]
The library was not being correctly updated. Thank you very much for your help!
