### ISSUE TITLE
Not able to build from source for com.github.erosb:everit-json-schema:1.14.4

### ISSUE THREAD

**Issue by imtavish04** [everit-org/json-schema#509]
I am trying to run "mvn clean install" for com.github.erosb:everit-json-schema:1.14.4. But the build is failing with the given error --> 

```
[ERROR] testInEarlyFailingMode{TestCase}[253]  Time elapsed: 130.956 s  <<< ERROR!
java.io.UncheckedIOException: java.net.ConnectException: Connection timed out
        at org.everit.json.schema.V4TestSuiteTest.testInEarlyFailingMode(V4TestSuiteTest.java:41)
Caused by: java.net.ConnectException: Connection timed out
        at org.everit.json.schema.V4TestSuiteTest.testInEarlyFailingMode(V4TestSuiteTest.java:41)
Caused by: java.net.ConnectException: Connection timed out
        at org.everit.json.schema.V4TestSuiteTest.testInEarlyFailingMode(V4TestSuiteTest.java:41)
```

I am using the following java and maven versions -> 

```
Apache Maven 3.9.4 (dfbb324ad4a7c8fb0bf182e6d91b0ae20e3d2dd9)
Maven home: /opt/apache-maven-3.9.4
Java version: 17.0.8, vendor: Oracle Corporation, runtime: /opt/jdk-17.0.8
Default locale: en_US, platform encoding: ANSI_X3.4-1968
OS name: "linux", version: "5.4.17-2136.308.9.el8uek.x86_64", arch: "amd64", family: "unix"
```

Please assist on how to resolve this issue.

**Comment by erosb** [comment]
Hello, can you please attach a full build log?

**Comment by imtavish04** [comment]
These are the logs 
[build.log](https://github.com/user-attachments/files/15986981/build.log)

**Comment by imtavish04** [comment]
Hi please find the attached build logs
[build.log](https://github.com/user-attachments/files/16007901/build.log)
