### ISSUE TITLE
Unable to validate array property. [key type: expected type is one of JSONArray, String, found: JSONObject]

### ISSUE THREAD

**Issue by sumit4myself** [everit-org/json-schema#71]
Code: 

		try{
		 String jsonData =
				 getStringFromInputStream(stringToStream(getRequestBody(jsonObject)));
		 
		String url = "http://localhost:"+port+"/schema/";
		Schema schema = SchemaLoader.builder().resolutionScope(url)
				.schemaJson(new JSONObject(
						new JSONTokener(JsonRequestValidator.class.getResourceAsStream(jsonFileName))))
				.build().load().build();
		
		schema.validate(new JSONObject(jsonData));
		}catch(IOException | ValidationException  e ) {
			logger.info("Error - > "+e);
		}

Schema: 
{
	"$schema": "http://json-schema.org/draft-04/schema#",
	"type": "object",
	"properties": {
		"GlobalData": {
			"type": "object",
			"properties": {
				"ConnectionModes": {
					"type": "array",
					"items": {
						"type": "object",
						"properties": {
							"Name": {
								"type": {
									"enum": [
										"Bridge",
										"Implicit NAT",
										"UPnP NAPT"
									]
								}
							},
							"Status": {
								"type": {
									"enum": [
										"Enabled",
										"Disabled"
									]
								}
							}
						}
					}
				}
			}
		}
	},
	"required": [
		"GlobalData"
	]
}
Json Data:
{
	"GlobalData": {
		"ConnectionModes": [
			{
				"Name": "Bridged",
				"Status": "Enabled"
			},
			{
				"Name": "UPnP",
				"Status": "Disabled"
			},
			{
				"Name": "Implicit NAT",
				"Status": "Enabled"
			}
		]
	}
}

org.everit.json.schema.SchemaException: key type: expected type is one of JSONArray, String, found: JSONObject
	at org.everit.json.schema.loader.SchemaLoader.loadForType(SchemaLoader.java:544) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:503) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:514) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.lambda$addPropertySchemaDefinition$5(SchemaLoader.java:316) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl.lambda$then$0(TypeBasedMultiplexer.java:76) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.orElse(TypeBasedMultiplexer.java:231) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.requireAny(TypeBasedMultiplexer.java:241) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.addPropertySchemaDefinition(SchemaLoader.java:318) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.lambda$populatePropertySchemas$16(SchemaLoader.java:581) ~[org.everit.json.schema-1.4.1.jar:na]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_66]
	at org.everit.json.schema.loader.SchemaLoader.populatePropertySchemas(SchemaLoader.java:580) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.lambda$buildObjectSchema$9(SchemaLoader.java:385) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl.lambda$then$0(TypeBasedMultiplexer.java:76) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.orElse(TypeBasedMultiplexer.java:231) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.requireAny(TypeBasedMultiplexer.java:241) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.buildObjectSchema(SchemaLoader.java:386) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.loadForExplicitType(SchemaLoader.java:532) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.loadForType(SchemaLoader.java:542) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:503) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:514) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.lambda$buildArraySchema$7(SchemaLoader.java:347) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl.lambda$then$0(TypeBasedMultiplexer.java:76) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.orElse(TypeBasedMultiplexer.java:231) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.requireAny(TypeBasedMultiplexer.java:241) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.buildArraySchema(SchemaLoader.java:349) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.loadForExplicitType(SchemaLoader.java:530) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.loadForType(SchemaLoader.java:542) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:503) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:514) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.lambda$addPropertySchemaDefinition$5(SchemaLoader.java:316) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl.lambda$then$0(TypeBasedMultiplexer.java:76) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.orElse(TypeBasedMultiplexer.java:231) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.requireAny(TypeBasedMultiplexer.java:241) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.addPropertySchemaDefinition(SchemaLoader.java:318) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.lambda$populatePropertySchemas$16(SchemaLoader.java:581) ~[org.everit.json.schema-1.4.1.jar:na]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_66]
	at org.everit.json.schema.loader.SchemaLoader.populatePropertySchemas(SchemaLoader.java:580) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.lambda$buildObjectSchema$9(SchemaLoader.java:385) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl.lambda$then$0(TypeBasedMultiplexer.java:76) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.orElse(TypeBasedMultiplexer.java:231) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.requireAny(TypeBasedMultiplexer.java:241) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.buildObjectSchema(SchemaLoader.java:386) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.loadForExplicitType(SchemaLoader.java:532) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.loadForType(SchemaLoader.java:542) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:503) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:514) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.lambda$addPropertySchemaDefinition$5(SchemaLoader.java:316) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl.lambda$then$0(TypeBasedMultiplexer.java:76) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.orElse(TypeBasedMultiplexer.java:231) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.requireAny(TypeBasedMultiplexer.java:241) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.addPropertySchemaDefinition(SchemaLoader.java:318) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.lambda$populatePropertySchemas$16(SchemaLoader.java:581) ~[org.everit.json.schema-1.4.1.jar:na]
	at java.util.Spliterators$ArraySpliterator.forEachRemaining(Spliterators.java:948) ~[na:1.8.0_66]
	at java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:580) ~[na:1.8.0_66]
	at org.everit.json.schema.loader.SchemaLoader.populatePropertySchemas(SchemaLoader.java:580) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.lambda$buildObjectSchema$9(SchemaLoader.java:385) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl.lambda$then$0(TypeBasedMultiplexer.java:76) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.orElse(TypeBasedMultiplexer.java:231) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.requireAny(TypeBasedMultiplexer.java:241) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.buildObjectSchema(SchemaLoader.java:386) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.loadForExplicitType(SchemaLoader.java:532) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.loadForType(SchemaLoader.java:542) ~[org.everit.json.schema-1.4.1.jar:na]
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:503) ~[org.everit.json.schema-1.4.1.jar:na]

**Comment by erosb** [comment]
Hi, the schema fragment describing the Status key is malformed. You can find an example of using enum in JSON Schema here: http://json-schema.org/example2.html

**Comment by sumit4myself** [comment]
Hi Bence,

Please let me know the problem in enum deceleration in my schema, I have cross checked with JSON Schema http://json-schema.org/example2.html and i haven't found any problem.

"Name": {
                "type": { "enum": [ "Bridge", "Implicit NAT", "UPnP NAPT" ] }
}

**Comment by erosb** [comment]
The `"type"` keyword shouldn't be there. Properly it is

```
"Name": {
  "enum": [ "Bridge", "Implicit NAT", "UPnP NAPT" ] 
}
```

**Comment by sumit4myself** [comment]
thanks Bence
