### ISSUE TITLE
java7 version enum issue

### ISSUE THREAD

**Issue by mattijevi** [everit-org/json-schema#75]
Not sure if I should leave this issue here or somewhere else because it has to do with the java 7 version.

I have a schema entry that looks like this:
`    "taxRate": {
      "type": "integer",
      "required": true,
      "enum": [
        0,
        16
      ]
    },`

When I attempt to use it to validate json I get the following:
java.lang.NoSuchMethodError: org.json.JSONArray.iterator()Ljava/util/Iterator;

	at org.everit.json.schema.loader.SchemaLoader.buildEnumSchema(SchemaLoader.java:241)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:312)
	at org.everit.json.schema.loader.SchemaLoader.loadChild(SchemaLoader.java:397)
	at org.everit.json.schema.loader.ObjectSchemaLoader$7.accept(ObjectSchemaLoader.java:109)
	at org.everit.json.schema.loader.ObjectSchemaLoader$7.accept(ObjectSchemaLoader.java:106)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl$1.accept(TypeBasedMultiplexer.java:86)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl$1.accept(TypeBasedMultiplexer.java:74)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.orElse(TypeBasedMultiplexer.java:251)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.requireAny(TypeBasedMultiplexer.java:261)
	at org.everit.json.schema.loader.ObjectSchemaLoader.addPropertySchemaDefinition(ObjectSchemaLoader.java:112)
	at org.everit.json.schema.loader.ObjectSchemaLoader.populatePropertySchemas(ObjectSchemaLoader.java:98)
	at org.everit.json.schema.loader.ObjectSchemaLoader.access$000(ObjectSchemaLoader.java:13)
	at org.everit.json.schema.loader.ObjectSchemaLoader$3.accept(ObjectSchemaLoader.java:44)
	at org.everit.json.schema.loader.ObjectSchemaLoader$3.accept(ObjectSchemaLoader.java:40)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl$1.accept(TypeBasedMultiplexer.java:86)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer$IdModifyingTypeConsumerImpl$1.accept(TypeBasedMultiplexer.java:74)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.orElse(TypeBasedMultiplexer.java:251)
	at org.everit.json.schema.loader.internal.TypeBasedMultiplexer.requireAny(TypeBasedMultiplexer.java:261)
	at org.everit.json.schema.loader.ObjectSchemaLoader.load(ObjectSchemaLoader.java:46)
	at org.everit.json.schema.loader.SchemaLoader.buildObjectSchema(SchemaLoader.java:369)
	at org.everit.json.schema.loader.SchemaLoader.loadForExplicitType(SchemaLoader.java:362)
	at org.everit.json.schema.loader.SchemaLoader.loadForType(SchemaLoader.java:380)
	at org.everit.json.schema.loader.SchemaLoader$6.get(SchemaLoader.java:321)
	at com.google.common.base.Absent.or(Absent.java:65)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:315)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:182)
	at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:167)

It appears to be in this method:
`    private EnumSchema.Builder buildEnumSchema() {
        JSONArray arr = ls.schemaJson.getJSONArray("enum");
        Set<Object> possibleValues = Sets.newHashSet(arr.iterator());
        return EnumSchema.builder().possibleValues(possibleValues);
    }
`

This is my gradle entry:
compile(group: "com.doctusoft", name: "json-schema-java7", version: "1.4.1")

**Comment by erosb** [comment]
Hello, could you please file an issue here? https://github.com/Doctusoft/json-schema
