### ISSUE TITLE
NullPointerException on empy dependencies

### ISSUE THREAD

**Issue by jmfernandez** [everit-org/json-schema#85]
When a JSON Schema has an empty `dependencies` hash, like next:

```json
{
  "type": "object",
  "properties": {
    "foo": {
      "type":"string"
    }
  },
  "dependencies": {}
}
```

`SchemaLoader.load` fires next NullPointerException for previous schema:

```
        at java.util.Arrays.stream(Arrays.java:5004)
        at org.everit.json.schema.loader.ObjectSchemaLoader.addDependencies(ObjectSchemaLoader.java:85)
        at org.everit.json.schema.loader.ObjectSchemaLoader.lambda$load$2(ObjectSchemaLoader.java:59)
        at org.everit.json.schema.loader.LoadingState.ifPresent(LoadingState.java:56)
        at org.everit.json.schema.loader.ObjectSchemaLoader.load(ObjectSchemaLoader.java:59)
        at org.everit.json.schema.loader.SchemaLoader.buildObjectSchema(SchemaLoader.java:324)
        at org.everit.json.schema.loader.SchemaLoader.loadForExplicitType(SchemaLoader.java:317)
        at org.everit.json.schema.loader.SchemaLoader.loadForType(SchemaLoader.java:335)
        at org.everit.json.schema.loader.SchemaLoader.lambda$load$0(SchemaLoader.java:292)
        at java.util.Optional.orElseGet(Optional.java:267)
        at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:288)
        at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:178)
        at org.everit.json.schema.loader.SchemaLoader.load(SchemaLoader.java:163)
```

despite being a valid JSON Schema. I have got this issue while testing version 1.5.1 , obtained from a Maven repository.

**Comment by erosb** [comment]
Thanks for reporting it. I could reproduce it with version `1.5.1` , but I couldn't with latest `master` revision. So you can wait for the next release with the fix, or use the current HEAD, by using this dependency:

```
<dependency>
        <groupId>com.github.everit-org.json-schema</groupId>
        <artifactId>org.everit.json.schema</artifactId>
        <version>dc383ce65bf5a7b97b699763f8441aa278dfb365</version>
 </dependency>
```

**Comment by erosb** [comment]
Hello @jmfernandez  , I released the new version yesterday.

Links:
* [Release notes](https://github.com/everit-org/json-schema/releases/tag/1.6.0)
* [Installation instructions](https://github.com/everit-org/json-schema#maven-installation)
